### ISSUE TITLE
Application keep stopping after building with code assist

### ISSUE THREAD

**Issue by MamusXS** [tyron12233/CodeAssist#113]
My application just keep stopping after building with the AndroidX template on my smartphone with Android version 11. It's there any new version of the Code Assist where this bug was fixed.

**Comment by tyron12233** [comment]
Can you send the stack trace or the error logs?

**Comment by MamusXS** [comment]
> Can you send the stack trace or the error logs?

Build version: 0.1.6 ALPHA 
Build date: 1981-01-01 01:01:02 
Current date: 2021-12-29 18:32:51 
Device: TECNO MOBILE LIMITED TECNO CG6 
 
Stack trace:  
java.lang.IllegalArgumentException: text can not be null
	at io.github.rosemoe.sora.text.Content.replace(Content.java:399)
	at io.github.rosemoe.sora.widget.CodeEditor.lambda$onFormatSucceed$1$CodeEditor(CodeEditor.java:5110)
	at io.github.rosemoe.sora.widget.CodeEditor$$ExternalSyntheticLambda1.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:268)
	at android.app.ActivityThread.main(ActivityThread.java:7985)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:627)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)

User actions: 
2021-12-29 18:32:09: MainActivity created
2021-12-29 18:32:09: MainActivity resumed
2021-12-29 18:32:30: MainActivity paused
2021-12-29 18:32:38: MainActivity resumed

**Comment by rdm600** [comment]
@MamusXS Гадаю, сейчас разраб скажет, что это проблемы либы редактора, ничем помочь не сможет

**Comment by tyron12233** [comment]
you are still om v0.1.6 this issue has been already fixed on the latest version
