### ISSUE TITLE
Click <Refresh Project>

### ISSUE THREAD

**Issue by rdm600** [tyron12233/CodeAssist#114]
Build version: 0.1.9.1 ALPHA 
Build date: 1981-01-01 01:01:02 
Current date: 2021-12-29 12:53:31 
Device: Samsung SM-M215F 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
	at com.tyron.resolver.DependencyResolver.resolveDependencies(DependencyResolver.java:39)
	at com.tyron.code.ui.project.DependencyManager.resolve(DependencyManager.java:76)
	at com.tyron.code.ui.project.ProjectManager.downloadLibraries(ProjectManager.java:126)
	at com.tyron.code.ui.project.ProjectManager.doOpenProject(ProjectManager.java:93)
	at com.tyron.code.ui.project.ProjectManager.lambda$openProject$0$ProjectManager(ProjectManager.java:73)
	at com.tyron.code.ui.project.ProjectManager$$ExternalSyntheticLambda0.run(Unknown Source:10)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

User actions: 
2021-12-29 12:51:47: MainActivity created
2021-12-29 12:51:47: MainActivity resumed
2021-12-29 12:51:51: MainActivity paused
2021-12-29 12:51:51: SettingsActivity created
2021-12-29 12:51:51: SettingsActivity resumed
2021-12-29 12:51:57: SettingsActivity paused
2021-12-29 12:51:57: MainActivity resumed
2021-12-29 12:51:58: SettingsActivity destroyed
2021-12-29 12:51:59: MainActivity paused
2021-12-29 12:51:59: SettingsActivity created
2021-12-29 12:51:59: SettingsActivity resumed
2021-12-29 12:52:44: SettingsActivity paused
2021-12-29 12:52:56: SettingsActivity resumed
2021-12-29 12:53:03: SettingsActivity paused
2021-12-29 12:53:03: MainActivity resumed
2021-12-29 12:53:03: SettingsActivity destroyed

**Comment by tyron12233** [comment]
already fixed on [this](https://github.com/tyron12233/CodeAssist/commit/5bc64f66b583a35754c33c3067cf2dd4d6fbb409) commit thanks

**Comment by rdm600** [comment]
> already fixed on [this](https://github.com/tyron12233/CodeAssist/commit/5bc64f66b583a35754c33c3067cf2dd4d6fbb409) commit thanks

What should I do? I can't log in to the project after clicking this button, crash
