### ISSUE TITLE
Crash on Resolving Depedencies

### ISSUE THREAD

**Issue by thewolfprod** [tyron12233/CodeAssist#116]
The error occurs when I click on a project from the list. 
I remember that before last update where we can't add dependencies in build.gradle I duplicated the project to test something and something that i add did not work - Then I updated CodeAssist and went back to the original project and added libraries through the new feature, then I removed the duplicate project and I can't go back to the original now... 

libraries.json is empty... 

Build version: 0.1.9.1 ALPHA 
Build date: 1981-01-01 01:01:02 
Current date: 2021-12-29 19:10:29 
Device: HUAWEI SNE-LX1 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
	at com.tyron.resolver.DependencyResolver.resolveDependencies(DependencyResolver.java:39)
	at com.tyron.code.ui.project.DependencyManager.resolve(DependencyManager.java:76)
	at com.tyron.code.ui.project.ProjectManager.downloadLibraries(ProjectManager.java:126)
	at com.tyron.code.ui.project.ProjectManager.doOpenProject(ProjectManager.java:93)
	at com.tyron.code.ui.project.ProjectManager.lambda$openProject$0$ProjectManager(ProjectManager.java:73)
	at com.tyron.code.ui.project.ProjectManager$$ExternalSyntheticLambda0.run(Unknown Source:10)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)

User actions: 
2021-12-29 19:09:55: MainActivity created
2021-12-29 19:09:55: MainActivity resumed

**Comment by tyron12233** [comment]
Fixed on 0.2.1
