### ISSUE TITLE
Editor Crash

### ISSUE THREAD

**Issue by rdm600** [tyron12233/CodeAssist#134]
Build version: 0.2.2 ALPHA 
Build date: 1981-01-01 01:01:02 
Current date: 2022-01-10 21:01:40 
Device: Samsung SM-M215F 
 
Stack trace:  
java.lang.NullPointerException: Attempt to read from field 'int io.github.rosemoe.sora.text.CharPosition.line' on a null object reference
	at io.github.rosemoe.sora.text.CachedIndexer.findNearestByLine(CachedIndexer.java:131)
	at io.github.rosemoe.sora.text.CachedIndexer.getCharPosition(CachedIndexer.java:388)
	at io.github.rosemoe.sora.text.CachedIndexer.getCharIndex(CachedIndexer.java:352)
	at io.github.rosemoe.sora.text.Content.getCharIndex(Content.java:238)
	at io.github.rosemoe.sora.widget.CodeEditor.updateSelection(CodeEditor.java:4487)
	at io.github.rosemoe.sora.widget.EditorInputConnection.endBatchEdit(EditorInputConnection.java:361)
	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:483)
	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:93)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8595)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

User actions: 
2022-01-10 20:11:44: MainActivity created
2022-01-10 20:11:44: MainActivity resumed
2022-01-10 20:13:20: MainActivity paused
2022-01-10 20:13:29: MainActivity resumed
2022-01-10 20:13:52: MainActivity paused
2022-01-10 20:14:50: MainActivity resumed
2022-01-10 20:15:01: MainActivity paused
2022-01-10 20:15:21: MainActivity resumed
2022-01-10 20:17:09: MainActivity paused
2022-01-10 20:17:23: MainActivity resumed
2022-01-10 20:18:15: MainActivity paused
2022-01-10 20:18:19: MainActivity resumed
2022-01-10 20:22:09: MainActivity paused
2022-01-10 20:24:39: MainActivity resumed
2022-01-10 20:24:40: MainActivity paused
2022-01-10 20:29:56: MainActivity resumed
2022-01-10 20:31:30: MainActivity paused
2022-01-10 20:31:33: MainActivity resumed
2022-01-10 20:33:46: MainActivity paused
2022-01-10 20:34:00: MainActivity resumed
2022-01-10 20:37:18: MainActivity paused
2022-01-10 20:37:24: MainActivity resumed
2022-01-10 20:40:27: MainActivity paused
2022-01-10 20:40:30: MainActivity resumed
2022-01-10 20:40:48: MainActivity paused
2022-01-10 20:40:50: MainActivity resumed
2022-01-10 20:41:43: MainActivity paused
2022-01-10 20:42:15: MainActivity resumed
2022-01-10 20:42:26: MainActivity paused
2022-01-10 20:42:51: MainActivity resumed
2022-01-10 20:45:10: MainActivity paused
2022-01-10 20:45:19: MainActivity resumed
2022-01-10 20:46:04: MainActivity paused
2022-01-10 20:46:09: MainActivity resumed
2022-01-10 20:48:58: MainActivity paused
2022-01-10 20:49:07: MainActivity resumed
2022-01-10 20:49:13: MainActivity paused
2022-01-10 20:49:15: MainActivity resumed
2022-01-10 20:52:59: MainActivity paused
2022-01-10 20:53:03: MainActivity resumed
2022-01-10 20:56:45: MainActivity paused
2022-01-10 20:56:51: MainActivity resumed
2022-01-10 21:00:27: MainActivity paused
2022-01-10 21:00:32: MainActivity resumed

**Comment by tyron12233** [comment]
Turn of `enable keyboard suggestions` in settings

**Comment by rdm600** [comment]
> Turn of `enable keyboard suggestions` in settings

It was enabled and an error occurred

**Comment by tyron12233** [comment]
so turn it off

**Comment by tyron12233** [comment]
fixed in https://github.com/tyron12233/CodeAssist/commit/19dde71906b1396f32e0bdb2348c7dd402365056
