### ISSUE TITLE
Editor Crash

### ISSUE THREAD

**Issue by rdm600** [tyron12233/CodeAssist#141]
Build version: 0.2.2 ALPHA 
Build date: 1981-01-01 01:01:02 
Current date: 2022-01-16 15:22:32 
Device: Samsung SM-M215F 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.tyron.completion.java.JavaCompilerService.setCurrentModule(com.tyron.builder.project.api.JavaModule)' on a null object reference
	at com.tyron.completion.java.JavaCompilerProvider.getCompiler(JavaCompilerProvider.java:68)
	at com.tyron.completion.java.JavaCompletionProvider.complete(JavaCompletionProvider.java:82)
	at com.tyron.completion.java.JavaCompletionProvider.complete(JavaCompletionProvider.java:65)
	at com.tyron.completion.main.CompletionEngine.complete(CompletionEngine.java:59)
	at com.tyron.code.ui.editor.language.java.JavaAutoCompleteProvider.getAutoCompleteItems(JavaAutoCompleteProvider.java:55)
	at io.github.rosemoe.sora.widget.EditorAutoCompleteWindow$MatchThread.run(EditorAutoCompleteWindow.java:385)

User actions: 
2022-01-16 13:13:06: MainActivity created
2022-01-16 13:13:06: MainActivity resumed
2022-01-16 13:14:20: MainActivity paused
2022-01-16 13:14:20: MainActivity resumed
2022-01-16 13:14:22: MainActivity paused
2022-01-16 13:15:08: MainActivity resumed
2022-01-16 13:16:45: MainActivity paused
2022-01-16 13:16:45: MainActivity resumed
2022-01-16 13:16:46: MainActivity paused
2022-01-16 13:17:11: MainActivity resumed
2022-01-16 13:18:58: MainActivity paused
2022-01-16 13:21:29: MainActivity resumed
2022-01-16 13:21:38: MainActivity paused
2022-01-16 13:21:38: MainActivity resumed
2022-01-16 13:21:39: MainActivity paused
2022-01-16 13:22:07: MainActivity resumed
2022-01-16 13:22:33: MainActivity paused
2022-01-16 13:22:47: MainActivity resumed
2022-01-16 13:23:47: MainActivity paused
2022-01-16 13:23:47: MainActivity resumed
2022-01-16 13:23:48: MainActivity paused
2022-01-16 13:24:19: MainActivity resumed
2022-01-16 13:24:27: MainActivity paused
2022-01-16 13:27:07: MainActivity resumed
2022-01-16 13:27:17: MainActivity paused
2022-01-16 13:28:36: MainActivity resumed
2022-01-16 13:28:37: MainActivity paused
2022-01-16 13:30:07: MainActivity resumed
2022-01-16 13:30:26: MainActivity paused
2022-01-16 13:30:34: MainActivity resumed
2022-01-16 13:30:52: MainActivity paused
2022-01-16 13:30:56: MainActivity resumed
2022-01-16 13:31:59: MainActivity paused
2022-01-16 13:32:31: MainActivity resumed
2022-01-16 13:32:52: MainActivity paused
2022-01-16 13:33:14: MainActivity resumed
2022-01-16 13:33:15: MainActivity paused
2022-01-16 13:33:17: MainActivity resumed
2022-01-16 13:33:43: MainActivity paused
2022-01-16 13:34:00: MainActivity resumed
2022-01-16 13:35:01: MainActivity paused
2022-01-16 13:35:01: MainActivity resumed
2022-01-16 13:35:01: MainActivity paused
2022-01-16 13:35:40: MainActivity resumed
2022-01-16 13:36:26: MainActivity paused
2022-01-16 13:36:26: MainActivity resumed
2022-01-16 13:36:28: MainActivity paused
2022-01-16 13:37:30: MainActivity resumed
2022-01-16 13:37:33: MainActivity paused
2022-01-16 13:37:39: MainActivity resumed
2022-01-16 13:38:02: MainActivity paused
2022-01-16 13:38:03: MainActivity resumed
2022-01-16 13:38:13: MainActivity paused
2022-01-16 13:38:13: MainActivity resumed
2022-01-16 13:38:14: MainActivity paused
2022-01-16 13:38:48: MainActivity resumed
2022-01-16 13:38:51: MainActivity paused
2022-01-16 13:39:43: MainActivity resumed
2022-01-16 13:39:59: MainActivity paused
2022-01-16 13:39:59: MainActivity resumed
2022-01-16 13:40:00: MainActivity paused
2022-01-16 13:41:00: MainActivity resumed
2022-01-16 13:41:19: MainActivity paused
2022-01-16 13:41:25: MainActivity resumed
2022-01-16 13:41:26: MainActivity paused
2022-01-16 13:41:26: MainActivity resumed
2022-01-16 13:41:27: MainActivity paused
2022-01-16 13:42:09: MainActivity resumed
2022-01-16 13:42:35: MainActivity paused
2022-01-16 13:42:35: MainActivity resumed
2022-01-16 13:42:36: MainActivity paused
2022-01-16 13:43:01: MainActivity resumed
2022-01-16 13:43:09: MainActivity paused
2022-01-16 13:43:18: MainActivity resumed
2022-01-16 13:43:26: MainActivity paused
2022-01-16 13:43:26: MainActivity resumed
2022-01-16 13:43:27: MainActivity paused
2022-01-16 13:50:40: MainActivity resumed
2022-01-16 13:51:10: MainActivity paused
2022-01-16 13:51:29: MainActivity resumed
2022-01-16 13:51:46: MainActivity paused
2022-01-16 13:51:46: MainActivity resumed
2022-01-16 13:51:47: MainActivity paused
2022-01-16 13:53:59: MainActivity resumed
2022-01-16 13:54:10: MainActivity paused
2022-01-16 13:54:10: MainActivity resumed
2022-01-16 13:54:11: MainActivity paused
2022-01-16 13:56:31: MainActivity resumed
2022-01-16 13:59:13: MainActivity paused
2022-01-16 13:59:22: MainActivity resumed
2022-01-16 13:59:32: MainActivity paused
2022-01-16 13:59:32: MainActivity resumed
2022-01-16 13:59:33: MainActivity paused
2022-01-16 14:00:11: MainActivity resumed
2022-01-16 14:00:23: MainActivity paused
2022-01-16 14:00:26: MainActivity resumed
2022-01-16 14:00:54: MainActivity paused
2022-01-16 14:29:31: MainActivity resumed
2022-01-16 14:29:47: MainActivity paused
2022-01-16 14:29:47: MainActivity resumed
2022-01-16 14:29:48: MainActivity paused
2022-01-16 14:30:42: MainActivity resumed
2022-01-16 14:30:47: MainActivity paused
2022-01-16 14:31:09: MainActivity resumed
2022-01-16 14:31:24: MainActivity paused
2022-01-16 14:32:30: MainActivity resumed
2022-01-16 14:32:41: MainActivity paused
2022-01-16 14:32:41: MainActivity resumed
2022-01-16 14:32:44: MainActivity paused
2022-01-16 14:33:34: MainActivity resumed
2022-01-16 14:34:05: MainActivity paused
2022-01-16 14:35:59: MainActivity resumed
2022-01-16 14:36:09: MainActivity paused
2022-01-16 14:36:09: MainActivity resumed
2022-01-16 14:36:10: MainActivity paused
2022-01-16 14:40:53: MainActivity resumed
2022-01-16 14:41:00: MainActivity paused
2022-01-16 14:41:02: MainActivity resumed
2022-01-16 14:41:10: MainActivity paused
2022-01-16 14:46:48: MainActivity resumed
2022-01-16 14:50:36: MainActivity paused
2022-01-16 14:50:36: MainActivity resumed
2022-01-16 14:50:48: MainActivity paused
2022-01-16 15:02:27: MainActivity resumed
2022-01-16 15:05:25: MainActivity paused
2022-01-16 15:13:09: MainActivity resumed
2022-01-16 15:13:44: MainActivity paused
2022-01-16 15:14:38: MainActivity resumed
2022-01-16 15:15:17: MainActivity paused
2022-01-16 15:15:17: MainActivity resumed
2022-01-16 15:15:18: MainActivity paused
2022-01-16 15:16:34: MainActivity resumed
2022-01-16 15:17:37: MainActivity paused
2022-01-16 15:17:38: MainActivity resumed
2022-01-16 15:17:40: MainActivity paused
2022-01-16 15:18:56: MainActivity resumed
2022-01-16 15:20:57: MainActivity paused
2022-01-16 15:20:57: MainActivity resumed
2022-01-16 15:20:58: MainActivity paused
2022-01-16 15:21:43: MainActivity resumed

**Comment by tyron12233** [comment]
Fixed in 0.2.3
