### ISSUE TITLE
auto suggest when writing code in XML file

### ISSUE THREAD

**Issue by getsettalk** [tyron12233/CodeAssist#148]
Please give a update on XML, 
While I'm menually writing code in XML file ,than why not give auto suggest and auto complete word . Plese fix and sometimes crash preview layout.

**Comment by tyron12233** [comment]
There is already an autocomplete for xml, please join the discord server for development updates 

link: https://discord.gg/pffnyE6prs

**Comment by tyron12233** [comment]
Ill be closing this issue since its already implemented, for the layout preview crash open another issue providing more details.

**Comment by getsettalk** [comment]
A new issue:

Build version: 0.2.5 ALPHA
Build date: 1981-01-01 01:01:02
Current date: 2022-02-08 09:03:55
Device: Realme RMX1827

Stack trace:
java.lang.IllegalStateException: The content of the adapter has changed but
ListView did not receive a notification. Make sure the content of your
adapter is not modified from a background thread, but only from the UI
thread. Make sure your adapter calls notifyDataSetChanged() when its
content changes. [in ListView(-1, class android.widget.ListView) with
Adapter(class com.tyron.code.ui.editor.CodeAssistCompletionAdapter)]
 at android.widget.ListView.layoutChildren(ListView.java:1726)
 at android.widget.AbsListView.onTouchModeChanged(AbsListView.java:3921)
 at
android.view.ViewTreeObserver.dispatchOnTouchModeChanged(ViewTreeObserver.java:1150)
 at android.view.ViewRootImpl.ensureTouchModeLocally(ViewRootImpl.java:5285)
 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2927)
 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2062)
 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8459)
 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1057)
 at android.view.Choreographer.doCallbacks(Choreographer.java:881)
 at android.view.Choreographer.doFrame(Choreographer.java:808)
 at
android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1042)
 at android.os.Handler.handleCallback(Handler.java:883)
 at android.os.Handler.dispatchMessage(Handler.java:100)
 at android.os.Looper.loop(Looper.java:227)
 at android.app.ActivityThread.main(ActivityThread.java:7822)
 at java.lang.reflect.Method.invoke(Native Method)
 at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)

User actions:
2022-02-08 09:00:43: MainActivity created
2022-02-08 09:00:43: MainActivity resumed
2022-02-08 09:02:06: MainActivity paused
2022-02-08 09:02:06: SettingsActivity created
2022-02-08 09:02:06: SettingsActivity resumed
2022-02-08 09:02:08: SettingsActivity paused
2022-02-08 09:02:08: MainActivity resumed
2022-02-08 09:02:08: SettingsActivity destroyed



## showing like above when I'm writing code in Roso... Code editor
