### ISSUE TITLE
Suddenly happened, when I was changing progressbar color programmatically

### ISSUE THREAD

**Issue by smith8h** [tyron12233/CodeAssist#152]
Build version: 0.2.2 ALPHA 
Build date: 1981-01-01 01:01:02 
Current date: 2022-01-22 19:27:54 
Device: Xiaomi Redmi Note 6 Pro 
 
Stack trace:  
java.lang.NullPointerException: Attempt to read from field 'int io.github.rosemoe.sora.text.CharPosition.line' on a null object reference
	at io.github.rosemoe.sora.text.CachedIndexer.findNearestByLine(CachedIndexer.java:131)
	at io.github.rosemoe.sora.text.CachedIndexer.getCharPosition(CachedIndexer.java:388)
	at io.github.rosemoe.sora.text.CachedIndexer.getCharIndex(CachedIndexer.java:352)
	at io.github.rosemoe.sora.text.Content.getCharIndex(Content.java:238)
	at io.github.rosemoe.sora.widget.CodeEditor.updateSelection(CodeEditor.java:4487)
	at io.github.rosemoe.sora.widget.EditorInputConnection.endBatchEdit(EditorInputConnection.java:361)
	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:482)
	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:85)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6810)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

User actions: 
2022-01-22 19:17:32: MainActivity created
2022-01-22 19:17:32: MainActivity resumed
2022-01-22 19:22:51: MainActivity paused
2022-01-22 19:25:48: MainActivity resumed
2022-01-22 19:26:31: MainActivity paused
2022-01-22 19:26:45: MainActivity resumed

**Comment by tyron12233** [comment]
This is an issue with the code editor's text input connection, until it has been fixed please turn off `Enable keyboard suggestions` in settings. This option is now turned off by default in the next version
