### ISSUE TITLE
XML Autocompletion couldn't recognize the editor

### ISSUE THREAD

**Issue by BanDroid** [tyron12233/CodeAssist#154]
There's a bug when you open a project that is already open a active xml file, and you try to type inside the xml file, it would crash.

This could be fixed if there's a default xml editor, it could layout editor or rosemoe editor, there should be a default 1. So, after open a project that have active xml files in the editor, the autocompletion would work fine.

Here's the error logs:

Build version: 0.2.2 ALPHA 
Build date: 1981-01-01 01:01:02 
Current date: 2022-01-23 20:27:48 
Device: Xiaomi Redmi 5 Plus 
 
Stack trace:  
java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.TimSort.mergeHi(TimSort.java:899)
	at java.util.TimSort.mergeAt(TimSort.java:516)
	at java.util.TimSort.mergeForceCollapse(TimSort.java:457)
	at java.util.TimSort.sort(TimSort.java:254)
	at java.util.Arrays.sort(Arrays.java:1498)
	at java.util.ArrayList.sort(ArrayList.java:1470)
	at java.util.Collections.sort(Collections.java:201)
	at com.tyron.completion.xml.providers.XmlCompletionProvider.complete(XmlCompletionProvider.java:94)
	at com.tyron.completion.main.CompletionEngine.complete(CompletionEngine.java:83)
	at com.tyron.code.ui.editor.language.xml.XMLAutoCompleteProvider.getAutoCompleteItems(XMLAutoCompleteProvider.java:55)
	at io.github.rosemoe.sora.widget.EditorAutoCompleteWindow$MatchThread.run(EditorAutoCompleteWindow.java:385)

User actions: 
2022-01-23 20:26:48: MainActivity created
2022-01-23 20:26:49: MainActivity resumed

**Comment by tyron12233** [comment]
This is issue is about the sorting of completion items, can you specify what file are you editing (Manifest or a layout) and at which attribute name.

**Comment by BanDroid** [comment]
I'm changing activity_main.xml, and then close the project, and when i open the project again, activity_main already opened, and i type attribute of app:popupTheme, but before i finish typing, the app crashes, the error is above that i have give.

**Comment by tyron12233** [comment]
Should be fixed on the latest commits now, reopen this issue if you are still facing issues
