### ISSUE TITLE
CodeAssist Crashed - Project Doesn't Open Now

### ISSUE THREAD

**Issue by thewolfprod** [tyron12233/CodeAssist#158]
I typed `<View (with Space on end)` in my `activity_main.xml` and CodeAssist crashed - now i can't open my project because everytime when im trying to open, I get this error:

```
Build version: 0.2.4 ALPHA 
Build date: 1981-01-01 01:01:02 
Current date: 2022-01-29 14:23:18 
Device: Samsung SM-A505FN 
 
Stack trace:  
java.lang.IllegalStateException: No successful match so far
	at java.util.regex.Matcher.ensureMatch(Matcher.java:1189)
	at java.util.regex.Matcher.group(Matcher.java:456)
	at com.android.tools.aapt2.Aapt2Jni.executeBinary(Aapt2Jni.java:154)
	at com.android.tools.aapt2.Aapt2Jni.compile(Aapt2Jni.java:115)
	at com.tyron.builder.compiler.incremental.resource.IncrementalAapt2Task.compileProject(IncrementalAapt2Task.java:95)
	at com.tyron.builder.compiler.incremental.resource.IncrementalAapt2Task.run(IncrementalAapt2Task.java:57)
	at com.tyron.code.ui.project.ProjectManager.doOpenProject(ProjectManager.java:125)
	at com.tyron.code.ui.project.ProjectManager.lambda$openProject$0$ProjectManager(ProjectManager.java:80)
	at com.tyron.code.ui.project.ProjectManager$$ExternalSyntheticLambda0.run(Unknown Source:10)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

User actions: 
2022-01-29 14:23:12: MainActivity created
2022-01-29 14:23:12: MainActivity resumed
```

**Comment by tyron12233** [comment]
fixed in https://github.com/tyron12233/CodeAssist/commit/cdf00116da66b000bf896dd7a4ad3f46094f8eac#diff-a4c33a2a8625e63f9fe138313c8058e66833cd2da35fa028f75e113e111f9fc8, a workaround for this is to edit the xml file manually to correct the errors

**Comment by thewolfprod** [comment]
I did this workaround - it only makes the error appear a few seconds after opening the project. 
Will apk_debug.apk file be in Actions with this fix?
