### ISSUE TITLE
😐

### ISSUE THREAD

**Issue by ToastcodeDev** [tyron12233/CodeAssist#160]
Build version: 0.2.4 ALPHA 
Build date: 1981-01-01 01:01:02 
Current date: 2022-01-29 22:48:44 
Device: HUAWEI JKM-LX3 
 
Stack trace:  
java.lang.IllegalStateException: No successful match so far
	at java.util.regex.Matcher.ensureMatch(Matcher.java:1116)
	at java.util.regex.Matcher.group(Matcher.java:382)
	at com.android.tools.aapt2.Aapt2Jni.executeBinary(Aapt2Jni.java:154)
	at com.android.tools.aapt2.Aapt2Jni.compile(Aapt2Jni.java:115)
	at com.tyron.builder.compiler.incremental.resource.IncrementalAapt2Task.compileProject(IncrementalAapt2Task.java:95)
	at com.tyron.builder.compiler.incremental.resource.IncrementalAapt2Task.run(IncrementalAapt2Task.java:57)
	at com.tyron.code.ui.project.ProjectManager.doOpenProject(ProjectManager.java:125)
	at com.tyron.code.ui.project.ProjectManager.lambda$openProject$0$ProjectManager(ProjectManager.java:80)
	at com.tyron.code.ui.project.ProjectManager$$ExternalSyntheticLambda0.run(Unknown Source:10)
	at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:784)

User actions: 
2022-01-29 22:48:39: MainActivity created
2022-01-29 22:48:39: MainActivity resumed

**Comment by tyron12233** [comment]
Please take look at version 0.2.4.1[here](https://github.com/tyron12233/CodeAssist/releases/tag/ALPHA-0.2.4.1) and reopen this if its still not fixed.
