### ISSUE TITLE
Not running in debug apk

### ISSUE THREAD

**Issue by ArindamDas1985** [tyron12233/CodeAssist#161]
Hello I'm getting the error when I run the debug apk button 

It's good concept but please try to resolve the issue. Thanks in advance

Build version: 0.2.4 ALPHA 
Build date: 1981-01-01 01:01:02 
Current date: 2022-01-30 22:09:28 

 
Stack trace:  
java.lang.IllegalStateException: No successful match so far
	at java.util.regex.Matcher.ensureMatch(Matcher.java:1209)
	at java.util.regex.Matcher.group(Matcher.java:480)
	at com.android.tools.aapt2.Aapt2Jni.executeBinary(Aapt2Jni.java:154)
	at com.android.tools.aapt2.Aapt2Jni.compile(Aapt2Jni.java:115)
	at com.tyron.builder.compiler.incremental.resource.IncrementalAapt2Task.compileProject(IncrementalAapt2Task.java:95)
	at com.tyron.builder.compiler.incremental.resource.IncrementalAapt2Task.run(IncrementalAapt2Task.java:57)
	at com.tyron.code.ui.editor.language.xml.XMLAnalyzer$CompileRunnable.doGenerate(XMLAnalyzer.java:330)
	at com.tyron.code.ui.editor.language.xml.XMLAnalyzer$CompileRunnable.lambda$run$0$XMLAnalyzer$CompileRunnable(XMLAnalyzer.java:307)
	at com.tyron.code.ui.editor.language.xml.XMLAnalyzer$CompileRunnable$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

User actions: 
2022-01-30 22:04:52: MainActivity created
2022-01-30 22:04:52: MainActivity resumed

**Comment by tyron12233** [comment]
Please check this version https://github.com/tyron12233/CodeAssist/releases/tag/ALPHA-0.2.4.1
