### ISSUE TITLE
Crash while parsing layout

### ISSUE THREAD

**Issue by Mirivan** [tyron12233/CodeAssist#162]
`android:text="""`

> ^ Three quotes in a row

Build version: 0.2.4 ALPHA
Build date: 1981-01-01 01:01:02
Current date: 2022-01-31 08:35:11
Device: Xiaomi Redmi Note 7

Stack trace:
java.lang.IllegalStateException: No successful match so far
	at java.util.regex.Matcher.ensureMatch(Matcher.java:1189)
	at java.util.regex.Matcher.group(Matcher.java:456)
	at com.android.tools.aapt2.Aapt2Jni.executeBinary(Aapt2Jni.java:154)
	at com.android.tools.aapt2.Aapt2Jni.compile(Aapt2Jni.java:115)
	at com.tyron.builder.compiler.incremental.resource.IncrementalAapt2Task.compileProject(IncrementalAapt2Task.java:95)
	at com.tyron.builder.compiler.incremental.resource.IncrementalAapt2Task.run(IncrementalAapt2Task.java:57)
	at com.tyron.code.ui.project.ProjectManager.doOpenProject(ProjectManager.java:125)
	at com.tyron.code.ui.project.ProjectManager.lambda$openProject$0$ProjectManager(ProjectManager.java:80)
	at com.tyron.code.ui.project.ProjectManager$$ExternalSyntheticLambda0.run(Unknown Source:10)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)

User actions: 
2022-01-31 08:34:47: MainActivity created
2022-01-31 08:34:47: MainActivity resumed

**Comment by tyron12233** [comment]
Please check this version https://github.com/tyron12233/CodeAssist/releases/tag/ALPHA-0.2.4.1

**Comment by Mirivan** [comment]
> Please check this version https://github.com/tyron12233/CodeAssist/releases/tag/ALPHA-0.2.4.1

work fine, thanks
