### ISSUE TITLE
Keeps lagging, take a time to refresh suggestions (popup menu) and when delete something (holding delete button)

### ISSUE THREAD

**Issue by smith8h** [tyron12233/CodeAssist#175]
Build version: 0.2.4.1 ALPHA 
Build date: 1981-01-01 01:01:02 
Current date: 2022-02-04 19:28:56 
Device: Xiaomi Redmi Note 6 Pro 
 
Stack trace:  
java.lang.RuntimeException: 0
	at com.tyron.completion.java.compiler.CompileTask.root(CompileTask.java:31)
	at com.tyron.code.ui.editor.impl.text.rosemoe.CodeEditorFragment.lambda$onViewCreated$1$CodeEditorFragment(CodeEditorFragment.java:336)
	at com.tyron.code.ui.editor.impl.text.rosemoe.CodeEditorFragment$$ExternalSyntheticLambda6.accept(Unknown Source:6)
	at com.tyron.completion.java.compiler.CompilerContainer.run(CompilerContainer.java:57)
	at com.tyron.code.ui.editor.impl.text.rosemoe.CodeEditorFragment.lambda$onViewCreated$2$CodeEditorFragment(CodeEditorFragment.java:333)
	at com.tyron.code.ui.editor.impl.text.rosemoe.CodeEditorFragment$$ExternalSyntheticLambda0.onCreateContextMenu(Unknown Source:4)
	at android.view.View.createContextMenu(View.java:13352)
	at com.android.internal.view.menu.ContextMenuBuilder.showPopup(ContextMenuBuilder.java:100)
	at com.android.internal.policy.DecorView.showContextMenuForChildInternal(DecorView.java:821)
	at com.android.internal.policy.DecorView.showContextMenuForChild(DecorView.java:798)
	at android.view.ViewGroup.showContextMenuForChild(ViewGroup.java:948)
	at android.view.ViewGroup.showContextMenuForChild(ViewGroup.java:948)
	at android.view.ViewGroup.showContextMenuForChild(ViewGroup.java:948)
	at android.view.ViewGroup.showContextMenuForChild(ViewGroup.java:948)
	at android.view.ViewGroup.showContextMenuForChild(ViewGroup.java:948)
	at android.view.ViewGroup.showContextMenuForChild(ViewGroup.java:948)
	at android.view.ViewGroup.showContextMenuForChild(ViewGroup.java:948)
	at android.view.ViewGroup.showContextMenuForChild(ViewGroup.java:948)
	at android.view.ViewGroup.showContextMenuForChild(ViewGroup.java:948)
	at android.view.ViewGroup.showContextMenuForChild(ViewGroup.java:948)
	at android.view.ViewGroup.showContextMenuForChild(ViewGroup.java:948)
	at android.view.ViewGroup.showContextMenuForChild(ViewGroup.java:948)
	at android.view.ViewGroup.showContextMenuForChild(ViewGroup.java:948)
	at android.view.ViewGroup.showContextMenuForChild(ViewGroup.java:948)
	at android.view.ViewGroup.showContextMenuForChild(ViewGroup.java:948)
	at android.view.View.showContextMenu(View.java:6778)
	at com.tyron.code.ui.editor.impl.text.rosemoe.CodeEditorFragment.lambda$onViewCreated$3$CodeEditorFragment(CodeEditorFragment.java:361)
	at com.tyron.code.ui.editor.impl.text.rosemoe.CodeEditorFragment$$ExternalSyntheticLambda3.onLongPress(Unknown Source:2)
	at io.github.rosemoe.sora.widget.EditorTextActionWindow.onSelectedTextLongClicked(EditorTextActionWindow.java:210)
	at io.github.rosemoe.sora.widget.EditorTouchEventHandler.onLongPress(EditorTouchEventHandler.java:600)
	at io.github.rosemoe.sora.widget.EditorTouchEventHandler.onLongPress(EditorTouchEventHandler.java:542)
	at android.view.GestureDetector.dispatchLongPress(GestureDetector.java:779)
	at android.view.GestureDetector.access$200(GestureDetector.java:40)
	at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:293)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6810)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

User actions: 
2022-02-04 19:07:00: MainActivity created
2022-02-04 19:07:01: MainActivity resumed
2022-02-04 19:12:03: MainActivity paused
2022-02-04 19:22:44: MainActivity resumed

**Comment by tyron12233** [comment]
Do you have code completions and error highlighting turned off in settings? (for java)

**Comment by smith8h** [comment]
No, they're turned on

**Comment by tyron12233** [comment]
Please check version 0.2.5 if it still occurs

**Comment by tyron12233** [comment]
Im going to assume that this issue is already resolved, if you are still experiencing this feel free to reopen this issue.
