### ISSUE TITLE
Error updating modules in CodAssist

### ISSUE THREAD

**Issue by IsaacOfc** [tyron12233/CodeAssist#265]
I have a project in codassist that compiles the APK file normally and apparently there are no problems with the code, but after the 0.2.8 ALPHA update, when I click on the "Refresh Module" option the application shows a screen informing that an unexpected error has occurred, so I decided to create a new test project in the same directory to compare and when I clicked on "Refresh Module" there were no problems, I went back to my original project and clicked again on "Refresh Module" and instead of the error occurring, my MainActivity was temporarily replaced by MainActivity from the test project I had created until I restarted the app, I believe it is a bug of this update.

 - Device: Galaxy J7Neo
 - OS: Android
 - Version 9

I am using the latest version of the application 0.2.8 ALPHA

**Comment by tyron12233** [comment]
Please always attach the stack trace / error log. You can view it by pressing `show error log` on the error screen and copy it.

**Comment by IsaacOfc** [comment]
Error details:

Build version: 0.2.8 ALPHA 
Build date: 1981-01-01 01:01:02 
Current date: 2022-02-26 01:48:24 
Device: Samsung SM-J701MT 
 
Stack trace:  
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:9317)
	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1653)
	at android.view.View.requestLayout(View.java:24880)
	at android.view.View.requestLayout(View.java:24880)
	at android.view.View.requestLayout(View.java:24880)
	at android.view.View.requestLayout(View.java:24880)
	at android.view.View.requestLayout(View.java:24880)
	at android.view.View.requestLayout(View.java:24880)
	at android.view.View.requestLayout(View.java:24880)
	at android.view.View.requestLayout(View.java:24880)
	at androidx.drawerlayout.widget.DrawerLayout.requestLayout(DrawerLayout.java:1353)
	at android.view.View.requestLayout(View.java:24880)
	at android.view.View.requestLayout(View.java:24880)
	at android.view.View.requestLayout(View.java:24880)
	at android.view.View.requestLayout(View.java:24880)
	at android.view.View.requestLayout(View.java:24880)
	at android.view.View.requestLayout(View.java:24880)
	at android.view.View.requestLayout(View.java:24880)
	at androidx.recyclerview.widget.RecyclerView.requestLayout(RecyclerView.java:4586)
	at android.view.View.requestLayout(View.java:24880)
	at android.view.View.requestLayout(View.java:24880)
	at android.view.View.requestLayout(View.java:24880)
	at io.github.rosemoe.sora.widget.CodeEditor.setText(CodeEditor.java:4207)
	at io.github.rosemoe.sora.widget.CodeEditor.setText(CodeEditor.java:4176)
	at com.tyron.code.ui.editor.impl.text.rosemoe.CodeEditorFragment.readFile(CodeEditorFragment.java:570)
	at com.tyron.code.ui.editor.impl.text.rosemoe.CodeEditorFragment.onProjectOpen(CodeEditorFragment.java:544)
	at com.tyron.code.ui.project.ProjectManager.lambda$doOpenProject$1$com-tyron-code-ui-project-ProjectManager(ProjectManager.java:104)
	at com.tyron.code.ui.project.ProjectManager$$ExternalSyntheticLambda1.accept(Unknown Source:4)
	at java.util.ArrayList.forEach(ArrayList.java:1262)
	at com.tyron.code.ui.project.ProjectManager.doOpenProject(ProjectManager.java:104)
	at com.tyron.code.ui.project.ProjectManager.lambda$openProject$0$com-tyron-code-ui-project-ProjectManager(ProjectManager.java:87)
	at com.tyron.code.ui.project.ProjectManager$$ExternalSyntheticLambda0.run(Unknown Source:10)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

User actions: 
2022-02-26 01:47:53: MainActivity created
2022-02-26 01:47:53: MainActivity resumed

**Comment by tyron12233** [comment]
Thanks, it's been fixed here https://github.com/tyron12233/CodeAssist/commit/4bb82f4adf90ca71ca46d9541b9778129e4fb601
