### ISSUE TITLE
App crashes when trying to Format if Word Wrap is enabled

### ISSUE THREAD

**Issue by 54b1d** [tyron12233/CodeAssist#299]
To Reproduce:

>Start new project from template
Open any file in editor
Go to **Settings** - **Editor** - **Code Editor Settings** - Enable **Word Wrap mode**
Go back to editor & Press **Format** from menu

Error Details:

>Build version: 0.2.8.2 ALPHA 
Build date: 1981-01-01 01:01:02 
Current date: 2022-03-04 12:20:26 
Device: Xiaomi Redmi 5 (Android 10)

>Stack trace:  
java.lang.ArrayIndexOutOfBoundsException: length=22; index=-1
	at java.util.ArrayList.get(ArrayList.java:439)
	at io.github.rosemoe.sora.widget.layout.WordwrapLayout.findRow(WordwrapLayout.java:94)
	at io.github.rosemoe.sora.widget.layout.WordwrapLayout.afterDelete(WordwrapLayout.java:181)
	at io.github.rosemoe.sora.widget.CodeEditor.afterDelete(CodeEditor.java:5086)
	at io.github.rosemoe.sora.text.Content.dispatchAfterDelete(Content.java:834)
	at io.github.rosemoe.sora.text.Content.deleteInternal(Content.java:501)
	at io.github.rosemoe.sora.text.Content.replace(Content.java:521)
	at io.github.rosemoe.sora.widget.CodeEditor.lambda$onFormatSucceed$1$io-github-rosemoe-sora-widget-CodeEditor(CodeEditor.java:5144)
	at io.github.rosemoe.sora.widget.CodeEditor$$ExternalSyntheticLambda1.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

>User actions: 
2022-03-04 12:17:57: MainActivity created
2022-03-04 12:17:57: MainActivity resumed
2022-03-04 12:19:22: MainActivity paused
2022-03-04 12:19:23: MainActivity destroyed
2022-03-04 12:19:33: MainActivity created
2022-03-04 12:19:33: MainActivity resumed
2022-03-04 12:20:11: MainActivity paused
2022-03-04 12:20:12: SettingsActivity created
2022-03-04 12:20:12: SettingsActivity resumed
2022-03-04 12:20:13: SettingsActivity paused
2022-03-04 12:20:13: MainActivity resumed
2022-03-04 12:20:13: SettingsActivity destroyed
2022-03-04 12:20:15: MainActivity paused
2022-03-04 12:20:15: SettingsActivity created
2022-03-04 12:20:15: SettingsActivity resumed
2022-03-04 12:20:20: SettingsActivity paused
2022-03-04 12:20:20: MainActivity resumed
2022-03-04 12:20:20: SettingsActivity destroyed

**Comment by tyron12233** [comment]
I suggesting reporting it to sora-editor's [repository](https://github.com/Rosemoe/sora-editor/issues) as it seems like its an internal issue from there.

**Comment by 54b1d** [comment]
I installed sora editor demo. Found word wrap feature but no formatting option to test or reproduce similliar error.

I'm unsure how I can report it to sora-editor's repository as I don't have in-depth knowledge.

Wouldn't it be better if you kindly forward the issue?

**Comment by Rohit24923** [comment]
> To Reproduce:
> 
> > Start new project from template
> > Open any file in editor
> > Go to **Settings** - **Editor** - **Code Editor Settings** - Enable **Word Wrap mode**
> > Go back to editor & Press **Format** from menu
> 
> Error Details:
> 
> > Build version: 0.2.8.2 ALPHA
> > Build date: 1981-01-01 01:01:02
> > Current date: 2022-03-04 12:20:26
> > Device: Xiaomi Redmi 5 (Android 10)
> 
> > Stack trace:
> > java.lang.ArrayIndexOutOfBoundsException: length=22; index=-1
> > at java.util.ArrayList.get(ArrayList.java:439)
> > at io.github.rosemoe.sora.widget.layout.WordwrapLayout.findRow(WordwrapLayout.java:94)
> > at io.github.rosemoe.sora.widget.layout.WordwrapLayout.afterDelete(WordwrapLayout.java:181)
> > at io.github.rosemoe.sora.widget.CodeEditor.afterDelete(CodeEditor.java:5086)
> > at io.github.rosemoe.sora.text.Content.dispatchAfterDelete(Content.java:834)
> > at io.github.rosemoe.sora.text.Content.deleteInternal(Content.java:501)
> > at io.github.rosemoe.sora.text.Content.replace(Content.java:521)
> > at io.github.rosemoe.sora.widget.CodeEditor.lambda$onFormatSucceed$1$io-github-rosemoe-sora-widget-CodeEditor(CodeEditor.java:5144)
> > at io.github.rosemoe.sora.widget.CodeEditor$$ExternalSyntheticLambda1.run(Unknown Source:4)
> > at android.os.Handler.handleCallback(Handler.java:883)
> > at android.os.Handler.dispatchMessage(Handler.java:100)
> > at android.os.Looper.loop(Looper.java:214)
> > at android.app.ActivityThread.main(ActivityThread.java:7356)
> > at java.lang.reflect.Method.invoke(Native Method)
> > at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
> > at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
> 
> > User actions:
> > 2022-03-04 12:17:57: MainActivity created
> > 2022-03-04 12:17:57: MainActivity resumed
> > 2022-03-04 12:19:22: MainActivity paused
> > 2022-03-04 12:19:23: MainActivity destroyed
> > 2022-03-04 12:19:33: MainActivity created
> > 2022-03-04 12:19:33: MainActivity resumed
> > 2022-03-04 12:20:11: MainActivity paused
> > 2022-03-04 12:20:12: SettingsActivity created
> > 2022-03-04 12:20:12: SettingsActivity resumed
> > 2022-03-04 12:20:13: SettingsActivity paused
> > 2022-03-04 12:20:13: MainActivity resumed
> > 2022-03-04 12:20:13: SettingsActivity destroyed
> > 2022-03-04 12:20:15: MainActivity paused
> > 2022-03-04 12:20:15: SettingsActivity created
> > 2022-03-04 12:20:15: SettingsActivity resumed
> > 2022-03-04 12:20:20: SettingsActivity paused
> > 2022-03-04 12:20:20: MainActivity resumed
> > 2022-03-04 12:20:20: SettingsActivity destroyed

This issue resolved by Rosemoe
![Screenshot_20220305-111417](https://user-images.githubusercontent.com/100986884/156870036-01d0f72a-4152-44e3-a42d-84f8381247b9.png)
