### ISSUE TITLE
Error when creating new project and loading it

### ISSUE THREAD

**Issue by PranavPurwar** [tyron12233/CodeAssist#31]
Build version: 1.0 
Build date: 1981-01-01 01:01:02 
Current date: 2021-11-28 14:21:40 
Device: Xiaomi Redmi Note 5 Pro 
 
Stack trace:  
java.lang.NullPointerException: Attempt to read from field 'org.openjdk.source.util.JavacTask com.tyron.completion.CompileBatch.task' on a null object reference
	at com.tyron.completion.JavaCompilerService.compile(JavaCompilerService.java:386)
	at com.tyron.completion.JavaCompilerService.compile(JavaCompilerService.java:372)
	at com.tyron.completion.provider.CompletionEngine.index(CompletionEngine.java:113)
	at com.tyron.ProjectManager.lambda$openProject$2$ProjectManager(ProjectManager.java:97)
	at com.tyron.ProjectManager$$ExternalSyntheticLambda6.run(Unknown Source:10)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

User actions: 
2021-11-28 14:18:18: MainActivity created
2021-11-28 14:18:19: MainActivity resumed
2021-11-28 14:18:19: MainActivity paused
2021-11-28 14:18:20: MainActivity resumed
2021-11-28 14:19:57: MainActivity paused
2021-11-28 14:19:57: SettingsActivity created
2021-11-28 14:19:57: SettingsActivity resumed
2021-11-28 14:20:04: SettingsActivity paused
2021-11-28 14:20:04: MainActivity resumed
2021-11-28 14:20:05: SettingsActivity destroyed
2021-11-28 14:20:38: MainActivity paused
2021-11-28 14:20:38: SettingsActivity created
2021-11-28 14:20:39: SettingsActivity resumed
2021-11-28 14:20:47: SettingsActivity paused
2021-11-28 14:20:47: MainActivity resumed
2021-11-28 14:20:48: SettingsActivity destroyed
2021-11-28 14:21:02: MainActivity paused
2021-11-28 14:21:03: MainActivity destroyed
2021-11-28 14:21:04: MainActivity created
2021-11-28 14:21:04: MainActivity resumed

**Comment by PranavPurwar** [comment]
It happens again and again when I open that blank kotlin project

**Comment by PranavPurwar** [comment]
When indexing the project

**Comment by PranavPurwar** [comment]
Some info:
Installed code assist from github actions
Java project works fine, but kotlin project crashes the app

**Comment by gdb417** [comment]
I confirm this.

**Comment by PranavPurwar** [comment]
yes

**Comment by alluhemanth27** [comment]
We are already aware of it and It happens when you don't have java files in your project, add a java file for temporary fix

**Comment by PranavPurwar** [comment]
ok, i will try tomorrow

**Comment by tyron12233** [comment]
fixed in https://github.com/tyron12233/CodeAssist/commit/accbfae019388c5780c7b019b75201ba5267f13b

**Comment by PranavPurwar** [comment]
👍

**Comment by TimScriptov** [comment]
CodeAssist good project 👍

**Comment by PranavPurwar** [comment]
yes
