### ISSUE TITLE
Layout Preview error

### ISSUE THREAD

**Issue by abodinagdat16** [tyron12233/CodeAssist#391]
# when i clicked to layout preview suddenly app crashed 
and there are another error in arabia language 
...... plz look at screen shot
![Screenshot_20220403_173058_com tyron code](https://user-images.githubusercontent.com/69758268/161433103-2354180d-c341-4cc1-9868-c0c01f3cd4dc.jpg)

*Build version: 0.2.9 ALPHA 
Build date: 1981-01-01 01:01:02 
Current date: 2022-04-03 17:30:30 
Device: HUAWEI INE-LX1r 
 
Stack trace:  
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.AbstractStringBuilder.substring(AbstractStringBuilder.java:954)
	at java.lang.StringBuilder.substring(StringBuilder.java:77)
	at com.flipkart.android.proteus.value.Gravity.getAsString(Gravity.java:57)
	at com.flipkart.android.proteus.value.Gravity.toString(Gravity.java:68)
	at com.tyron.code.ui.layoutEditor.LayoutEditorFragment.lambda$new$4$com-tyron-code-ui-layoutEditor-LayoutEditorFragment(LayoutEditorFragment.java:123)
	at com.tyron.code.ui.layoutEditor.LayoutEditorFragment$$ExternalSyntheticLambda0.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:6659)
	at android.view.View.performClickInternal(View.java:6631)
	at android.view.View.access$3100(View.java:790)
	at android.view.View$PerformClick.run(View.java:26187)
	at android.os.Handler.handleCallback(Handler.java:907)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

User actions: 
2022-04-03 17:30:03: MainActivity created
2022-04-03 17:30:03: MainActivity resumed

**Comment by rdm600** [comment]
@abodinagdat16 Вот и первые баги пошли

**Comment by LNDEVIL** [comment]
@rdm600 Да, ох уж эти баги!
