### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by MoonKnight18** [tyron12233/CodeAssist#411]
Build version: 0.2.9 ALPHA 
Build date: 1981-01-01 01:01:02 
Current date: 2022-04-11 16:49:39 
Device: Xiaomi Redmi 8 
 
Stack trace:  
java.lang.IndexOutOfBoundsException: Index: 53, Size: 3
	at java.util.ArrayList.get(ArrayList.java:437)
	at com.tyron.code.language.textmate.BaseIncrementalAnalyzeManager$LockedSpans$ReaderImpl.getSpanAt(BaseIncrementalAnalyzeManager.java:428)
	at io.github.rosemoe.sora.widget.EditorPainter.updateLineDisplayList(EditorPainter.java:268)
	at io.github.rosemoe.sora.widget.HwAcceleratedRenderer.drawLineHardwareAccelerated(HwAcceleratedRenderer.java:127)
	at io.github.rosemoe.sora.widget.EditorPainter.drawRows(EditorPainter.java:1014)
	at io.github.rosemoe.sora.widget.EditorPainter.drawView(EditorPainter.java:464)
	at io.github.rosemoe.sora.widget.EditorPainter.draw(EditorPainter.java:128)
	at io.github.rosemoe.sora.widget.CodeEditor.onDraw(CodeEditor.java:3268)
	at com.tyron.code.ui.editor.impl.text.rosemoe.CodeEditorView.onDraw(CodeEditorView.java:456)
	at android.view.View.draw(View.java:21546)
	at android.view.View.updateDisplayListIfDirty(View.java:20415)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4401)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4374)
	at android.view.View.updateDisplayListIfDirty(View.java:20375)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4401)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4374)
	at android.view.View.updateDisplayListIfDirty(View.java:20375)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4401)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4374)
	at android.view.View.updateDisplayListIfDirty(View.java:20375)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4401)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4374)
	at android.view.View.updateDisplayListIfDirty(View.java:20375)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4401)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4374)
	at android.view.View.updateDisplayListIfDirty(View.java:20375)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4401)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4374)
	at android.view.View.updateDisplayListIfDirty(View.java:20375)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4401)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4374)
	at android.view.View.updateDisplayListIfDirty(View.java:20375)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4401)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4374)
	at android.view.View.updateDisplayListIfDirty(View.java:20375)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4401)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4374)
	at android.view.View.updateDisplayListIfDirty(View.java:20375)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4401)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4374)
	at android.view.View.updateDisplayListIfDirty(View.java:20375)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4401)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4374)
	at android.view.View.updateDisplayListIfDirty(View.java:20375)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4401)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4374)
	at android.view.View.updateDisplayListIfDirty(View.java:20375)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4401)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4374)
	at android.view.View.updateDisplayListIfDirty(View.java:20375)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4401)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4374)
	at android.view.View.updateDisplayListIfDirty(View.java:20375)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4401)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4374)
	at android.view.View.updateDisplayListIfDirty(View.java:20375)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4401)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4374)
	at android.view.View.updateDisplayListIfDirty(View.java:20375)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4401)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4374)
	at android.view.View.updateDisplayListIfDirty(View.java:20375)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:575)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:581)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:654)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3700)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3495)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2832)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1785)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7747)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1031)
	at android.view.Choreographer.doCallbacks(Choreographer.java:854)
	at android.view.Choreographer.doFrame(Choreographer.java:789)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1016)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

User actions: 
2022-04-11 16:29:47: MainActivity created
2022-04-11 16:29:47: MainActivity resumed
2022-04-11 16:30:22: MainActivity paused
2022-04-11 16:32:53: MainActivity resumed
2022-04-11 16:32:55: MainActivity paused
2022-04-11 16:33:00: MainActivity resumed
2022-04-11 16:33:32: MainActivity paused
2022-04-11 16:33:44: MainActivity resumed
2022-04-11 16:35:14: MainActivity paused
2022-04-11 16:35:27: MainActivity resumed
2022-04-11 16:38:38: MainActivity paused
2022-04-11 16:41:25: MainActivity resumed
2022-04-11 16:42:10: MainActivity paused
2022-04-11 16:42:29: MainActivity resumed
2022-04-11 16:45:10: MainActivity paused
2022-04-11 16:47:53: MainActivity resumed

**Comment by tyron12233** [comment]
How many accounts are you going to create?

**Comment by rdm600** [comment]
@tyron12233 Ахахахаха
