### ISSUE TITLE
有时候输入东西会崩溃

### ISSUE THREAD

**Issue by yz-gm** [tyron12233/CodeAssist#412]
这些是崩溃日志

Build version: 0.2.8.3 ALPHA 
Build date: 1981-01-01 01:01:02 
Current date: 2022-04-11 23:06:36 
Device: Xiaomi M2012K11AC 
 
Stack trace:  
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.get(ArrayList.java:437)
	at com.tyron.code.language.textmate.BaseIncrementalAnalyzeManager$LockedSpans$ReaderImpl.getSpanAt(BaseIncrementalAnalyzeManager.java:428)
	at io.github.rosemoe.sora.widget.EditorPainter.updateLineDisplayList(EditorPainter.java:395)
	at io.github.rosemoe.sora.widget.HwAcceleratedRenderer.drawLineHardwareAccelerated(HwAcceleratedRenderer.java:127)
	at io.github.rosemoe.sora.widget.EditorPainter.drawRows(EditorPainter.java:1014)
	at io.github.rosemoe.sora.widget.EditorPainter.drawView(EditorPainter.java:464)
	at io.github.rosemoe.sora.widget.EditorPainter.draw(EditorPainter.java:128)
	at io.github.rosemoe.sora.widget.CodeEditor.onDraw(CodeEditor.java:3268)
	at com.tyron.code.ui.editor.impl.text.rosemoe.CodeEditorView.onDraw(CodeEditorView.java:456)
	at android.view.View.draw(Unknown Source:78)
	at android.view.View.updateDisplayListIfDirty(Unknown Source:218)
	at android.view.ViewGroup.recreateChildDisplayList(Unknown Source:21)
	at android.view.ViewGroup.dispatchGetDisplayList(Unknown Source:21)
	at android.view.View.updateDisplayListIfDirty(Unknown Source:88)
	at android.view.ViewGroup.recreateChildDisplayList(Unknown Source:21)
	at android.view.ViewGroup.dispatchGetDisplayList(Unknown Source:21)
	at android.view.View.updateDisplayListIfDirty(Unknown Source:88)
	at android.view.ViewGroup.recreateChildDisplayList(Unknown Source:21)
	at android.view.ViewGroup.dispatchGetDisplayList(Unknown Source:21)
	at android.view.View.updateDisplayListIfDirty(Unknown Source:88)
	at android.view.ViewGroup.recreateChildDisplayList(Unknown Source:21)
	at android.view.ViewGroup.dispatchGetDisplayList(Unknown Source:21)
	at android.view.View.updateDisplayListIfDirty(Unknown Source:88)
	at android.view.ViewGroup.recreateChildDisplayList(Unknown Source:21)
	at android.view.ViewGroup.dispatchGetDisplayList(Unknown Source:21)
	at android.view.View.updateDisplayListIfDirty(Unknown Source:88)
	at android.view.ViewGroup.recreateChildDisplayList(Unknown Source:21)
	at android.view.ViewGroup.dispatchGetDisplayList(Unknown Source:21)
	at android.view.View.updateDisplayListIfDirty(Unknown Source:88)
	at android.view.ViewGroup.recreateChildDisplayList(Unknown Source:21)
	at android.view.ViewGroup.dispatchGetDisplayList(Unknown Source:21)
	at android.view.View.updateDisplayListIfDirty(Unknown Source:88)
	at android.view.ViewGroup.recreateChildDisplayList(Unknown Source:21)
	at android.view.ViewGroup.dispatchGetDisplayList(Unknown Source:21)
	at android.view.View.updateDisplayListIfDirty(Unknown Source:88)
	at android.view.ViewGroup.recreateChildDisplayList(Unknown Source:21)
	at android.view.ViewGroup.dispatchGetDisplayList(Unknown Source:21)
	at android.view.View.updateDisplayListIfDirty(Unknown Source:88)
	at android.view.ViewGroup.recreateChildDisplayList(Unknown Source:21)
	at android.view.ViewGroup.dispatchGetDisplayList(Unknown Source:21)
	at android.view.View.updateDisplayListIfDirty(Unknown Source:88)
	at android.view.ViewGroup.recreateChildDisplayList(Unknown Source:21)
	at android.view.ViewGroup.dispatchGetDisplayList(Unknown Source:21)
	at android.view.View.updateDisplayListIfDirty(Unknown Source:88)
	at android.view.ViewGroup.recreateChildDisplayList(Unknown Source:21)
	at android.view.ViewGroup.dispatchGetDisplayList(Unknown Source:21)
	at android.view.View.updateDisplayListIfDirty(Unknown Source:88)
	at android.view.ViewGroup.recreateChildDisplayList(Unknown Source:21)
	at android.view.ViewGroup.dispatchGetDisplayList(Unknown Source:21)
	at android.view.View.updateDisplayListIfDirty(Unknown Source:88)
	at android.view.ViewGroup.recreateChildDisplayList(Unknown Source:21)
	at android.view.ViewGroup.dispatchGetDisplayList(Unknown Source:21)
	at android.view.View.updateDisplayListIfDirty(Unknown Source:88)
	at android.view.ViewGroup.recreateChildDisplayList(Unknown Source:21)
	at android.view.ViewGroup.dispatchGetDisplayList(Unknown Source:21)
	at android.view.View.updateDisplayListIfDirty(Unknown Source:88)
	at android.view.ViewGroup.recreateChildDisplayList(Unknown Source:21)
	at android.view.ViewGroup.dispatchGetDisplayList(Unknown Source:21)
	at android.view.View.updateDisplayListIfDirty(Unknown Source:88)
	at android.view.ViewGroup.recreateChildDisplayList(Unknown Source:21)
	at android.view.ViewGroup.dispatchGetDisplayList(Unknown Source:21)
	at android.view.View.updateDisplayListIfDirty(Unknown Source:88)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(Unknown Source:27)
	at android.view.ThreadedRenderer.updateRootDisplayList(Unknown Source:10)
	at android.view.ThreadedRenderer.draw(Unknown Source:7)
	at android.view.ViewRootImpl.draw(Unknown Source:399)
	at android.view.ViewRootImpl.performDraw(Unknown Source:64)
	at android.view.ViewRootImpl.performTraversals(Unknown Source:2719)
	at android.view.ViewRootImpl.doTraversal(Unknown Source:36)
	at android.view.ViewRootImpl$TraversalRunnable.run(Unknown Source:2)
	at android.view.Choreographer$CallbackRecord.run(Unknown Source:20)
	at android.view.Choreographer.doCallbacks(Unknown Source:84)
	at android.view.Choreographer.doFrame(Unknown Source:328)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Unknown Source:11)
	at android.os.Handler.handleCallback(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Unknown Source:4)
	at android.os.Looper.loopOnce(Unknown Source:176)
	at android.os.Looper.loop(Unknown Source:76)
	at android.app.ActivityThread.main(Unknown Source:138)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:306)

User actions: 
2022-04-11 22:52:30: MainActivity created
2022-04-11 22:52:30: MainActivity resumed
2022-04-11 22:52:31: MainActivity paused
2022-04-11 22:52:32: MainActivity resumed
2022-04-11 22:53:22: MainActivity paused
2022-04-11 22:53:31: MainActivity resumed
2022-04-11 22:53:40: MainActivity paused
2022-04-11 22:53:42: MainActivity resumed
2022-04-11 22:54:02: MainActivity paused
2022-04-11 22:54:02: MainActivity resumed
2022-04-11 22:54:06: MainActivity paused
2022-04-11 22:54:08: MainActivity resumed
2022-04-11 22:54:25: MainActivity paused
2022-04-11 22:54:25: MainActivity resumed
2022-04-11 22:54:27: MainActivity paused
2022-04-11 22:54:32: MainActivity resumed
2022-04-11 22:54:37: MainActivity paused
2022-04-11 22:55:11: MainActivity resumed
2022-04-11 22:56:59: MainActivity paused
2022-04-11 22:56:59: MainActivity resumed
2022-04-11 22:57:01: MainActivity paused
2022-04-11 22:57:06: MainActivity resumed
2022-04-11 22:57:11: MainActivity paused
2022-04-11 23:03:52: MainActivity resumed

**Comment by 17606657524** [comment]
用英文反馈老外看不懂
