### ISSUE TITLE
[NPE] Random crash while writing code 

### ISSUE THREAD

**Issue by Hax4us** [tyron12233/CodeAssist#47]
app is crashing randomly while writing code (java) 
here is logs

```
Build version: 1.0 
Build date: 1981-01-01 01:01:02 
Current date: 2021-12-12 12:31:45 
Device: Xiaomi Redmi Note 7 Pro 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewGroup$LayoutParams android.widget.PopupWindow$PopupDecorView.getLayoutParams()' on a null object reference
	at android.widget.PopupWindow.getDecorViewLayoutParams(PopupWindow.java:2201)
	at android.widget.PopupWindow.update(PopupWindow.java:2077)
	at io.github.rosemoe.sora.widget.EditorAutoCompleteWindow.lambda$displayResults$2$EditorAutoCompleteWindow(EditorAutoCompleteWindow.java:345)
	at io.github.rosemoe.sora.widget.-$$Lambda$EditorAutoCompleteWindow$WI9hPS5hbjuW0IUxEInYCWTgZGs.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6823)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

User actions: 
2021-12-12 10:33:44: MainActivity created
2021-12-12 10:33:45: MainActivity resumed
2021-12-12 10:35:18: MainActivity paused
2021-12-12 10:35:55: MainActivity resumed
2021-12-12 10:36:39: MainActivity paused
2021-12-12 10:36:44: MainActivity resumed
2021-12-12 10:36:52: MainActivity paused
2021-12-12 10:36:56: MainActivity resumed
2021-12-12 10:37:05: MainActivity paused
2021-12-12 10:37:08: MainActivity resumed
2021-12-12 10:37:14: MainActivity paused
2021-12-12 10:38:11: MainActivity resumed
2021-12-12 10:38:25: MainActivity paused
2021-12-12 10:38:31: MainActivity resumed
2021-12-12 10:40:17: MainActivity paused
2021-12-12 10:40:30: MainActivity resumed
2021-12-12 10:41:46: MainActivity paused
2021-12-12 11:36:28: MainActivity resumed
2021-12-12 11:37:10: MainActivity paused
2021-12-12 11:39:18: MainActivity resumed
2021-12-12 11:40:45: MainActivity paused
2021-12-12 11:42:29: MainActivity resumed
2021-12-12 11:46:41: MainActivity paused
2021-12-12 11:48:13: MainActivity resumed
2021-12-12 11:48:44: MainActivity paused
2021-12-12 11:49:11: MainActivity resumed
2021-12-12 11:49:33: MainActivity paused
2021-12-12 11:49:43: MainActivity resumed
2021-12-12 11:49:51: MainActivity paused
2021-12-12 11:49:56: MainActivity resumed
2021-12-12 11:50:04: MainActivity paused
2021-12-12 11:50:06: MainActivity resumed
2021-12-12 11:50:14: MainActivity paused
2021-12-12 11:50:16: MainActivity resumed
2021-12-12 11:55:38: MainActivity paused
2021-12-12 11:55:40: MainActivity resumed
2021-12-12 11:58:24: MainActivity paused
2021-12-12 11:58:32: MainActivity resumed
2021-12-12 11:58:34: MainActivity paused
2021-12-12 11:58:36: MainActivity resumed
2021-12-12 11:58:40: MainActivity paused
2021-12-12 11:58:42: MainActivity resumed
2021-12-12 11:58:53: MainActivity paused
2021-12-12 11:58:57: MainActivity resumed
2021-12-12 11:59:11: MainActivity paused
2021-12-12 11:59:14: MainActivity resumed
2021-12-12 12:00:35: MainActivity paused
2021-12-12 12:06:27: MainActivity resumed
2021-12-12 12:24:52: MainActivity paused
2021-12-12 12:25:02: MainActivity resumed
2021-12-12 12:25:22: MainActivity paused
2021-12-12 12:25:25: MainActivity resumed
2021-12-12 12:26:21: MainActivity paused
2021-12-12 12:27:50: MainActivity resumed
```

**Comment by rdm600** [comment]
> app is crashing randomly while writing code (java) here is logs
> 
> ```
> Build version: 1.0 
> Build date: 1981-01-01 01:01:02 
> Current date: 2021-12-12 12:31:45 
> Device: Xiaomi Redmi Note 7 Pro 
>  
> Stack trace:  
> java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewGroup$LayoutParams android.widget.PopupWindow$PopupDecorView.getLayoutParams()' on a null object reference
> 	at android.widget.PopupWindow.getDecorViewLayoutParams(PopupWindow.java:2201)
> 	at android.widget.PopupWindow.update(PopupWindow.java:2077)
> 	at io.github.rosemoe.sora.widget.EditorAutoCompleteWindow.lambda$displayResults$2$EditorAutoCompleteWindow(EditorAutoCompleteWindow.java:345)
> 	at io.github.rosemoe.sora.widget.-$$Lambda$EditorAutoCompleteWindow$WI9hPS5hbjuW0IUxEInYCWTgZGs.run(Unknown Source:4)
> 	at android.os.Handler.handleCallback(Handler.java:873)
> 	at android.os.Handler.dispatchMessage(Handler.java:99)
> 	at android.os.Looper.loop(Looper.java:201)
> 	at android.app.ActivityThread.main(ActivityThread.java:6823)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
> 
> User actions: 
> 2021-12-12 10:33:44: MainActivity created
> 2021-12-12 10:33:45: MainActivity resumed
> 2021-12-12 10:35:18: MainActivity paused
> 2021-12-12 10:35:55: MainActivity resumed
> 2021-12-12 10:36:39: MainActivity paused
> 2021-12-12 10:36:44: MainActivity resumed
> 2021-12-12 10:36:52: MainActivity paused
> 2021-12-12 10:36:56: MainActivity resumed
> 2021-12-12 10:37:05: MainActivity paused
> 2021-12-12 10:37:08: MainActivity resumed
> 2021-12-12 10:37:14: MainActivity paused
> 2021-12-12 10:38:11: MainActivity resumed
> 2021-12-12 10:38:25: MainActivity paused
> 2021-12-12 10:38:31: MainActivity resumed
> 2021-12-12 10:40:17: MainActivity paused
> 2021-12-12 10:40:30: MainActivity resumed
> 2021-12-12 10:41:46: MainActivity paused
> 2021-12-12 11:36:28: MainActivity resumed
> 2021-12-12 11:37:10: MainActivity paused
> 2021-12-12 11:39:18: MainActivity resumed
> 2021-12-12 11:40:45: MainActivity paused
> 2021-12-12 11:42:29: MainActivity resumed
> 2021-12-12 11:46:41: MainActivity paused
> 2021-12-12 11:48:13: MainActivity resumed
> 2021-12-12 11:48:44: MainActivity paused
> 2021-12-12 11:49:11: MainActivity resumed
> 2021-12-12 11:49:33: MainActivity paused
> 2021-12-12 11:49:43: MainActivity resumed
> 2021-12-12 11:49:51: MainActivity paused
> 2021-12-12 11:49:56: MainActivity resumed
> 2021-12-12 11:50:04: MainActivity paused
> 2021-12-12 11:50:06: MainActivity resumed
> 2021-12-12 11:50:14: MainActivity paused
> 2021-12-12 11:50:16: MainActivity resumed
> 2021-12-12 11:55:38: MainActivity paused
> 2021-12-12 11:55:40: MainActivity resumed
> 2021-12-12 11:58:24: MainActivity paused
> 2021-12-12 11:58:32: MainActivity resumed
> 2021-12-12 11:58:34: MainActivity paused
> 2021-12-12 11:58:36: MainActivity resumed
> 2021-12-12 11:58:40: MainActivity paused
> 2021-12-12 11:58:42: MainActivity resumed
> 2021-12-12 11:58:53: MainActivity paused
> 2021-12-12 11:58:57: MainActivity resumed
> 2021-12-12 11:59:11: MainActivity paused
> 2021-12-12 11:59:14: MainActivity resumed
> 2021-12-12 12:00:35: MainActivity paused
> 2021-12-12 12:06:27: MainActivity resumed
> 2021-12-12 12:24:52: MainActivity paused
> 2021-12-12 12:25:02: MainActivity resumed
> 2021-12-12 12:25:22: MainActivity paused
> 2021-12-12 12:25:25: MainActivity resumed
> 2021-12-12 12:26:21: MainActivity paused
> 2021-12-12 12:27:50: MainActivity resumed
> ```

Confirm. This was also the case with me. And what is your latest version? If not the last one, then most likely the developer has already fixed the problem

**Comment by Hax4us** [comment]
@rdm600 you were right.
