### ISSUE TITLE
flutter

### ISSUE THREAD

**Issue by PWashingtonE012** [tyron12233/CodeAssist#488]
**Note that Issues are for bugs only. Use the discussions tab for feature requests.**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**
Build version: 0.2.9 ALPHA 
Build date: 1981-01-01 01:01:02 
Current date: 2022-09-07 19:48:14 
Device: Motorola moto g stylus 5G 
 
Stack trace:  
android.os.NetworkOnMainThreadException
	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1683)
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:115)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
	at com.android.okhttp.Dns$1.lookup(Dns.java:41)
	at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:178)
	at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:144)
	at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:86)
	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:176)
	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:248)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
	at java.net.URL.openStream(URL.java:1072)
	at com.tyron.resolver.repository.RemoteRepository.getFileInternal(RemoteRepository.java:75)
	at com.tyron.resolver.repository.RemoteRepository.getFile(RemoteRepository.java:62)
	at com.tyron.resolver.repository.RemoteRepository.getInputStream(RemoteRepository.java:48)
	at com.tyron.resolver.repository.RepositoryManagerImpl.getFromUrls(RepositoryManagerImpl.java:94)
	at com.tyron.resolver.repository.RepositoryManagerImpl.getPomFromUrls(RepositoryManagerImpl.java:69)
	at com.tyron.resolver.repository.RepositoryManagerImpl.getPom(RepositoryManagerImpl.java:65)
	at com.tyron.resolver.parser.PomParser.parseParent(PomParser.java:160)
	at com.tyron.resolver.parser.PomParser.parseProject(PomParser.java:101)
	at com.tyron.resolver.parser.PomParser.parse(PomParser.java:78)
	at com.tyron.resolver.parser.PomParser.parse(PomParser.java:56)
	at com.tyron.resolver.repository.RepositoryManagerImpl.initialize(RepositoryManagerImpl.java:221)
	at com.tyron.code.ui.library.LibraryManagerFragment.onCreate(LibraryManagerFragment.java:95)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2981)
	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:474)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:257)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1758)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
	at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:488)
	at android.os.Handler.handleCallback(Handler.java:978)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loopOnce(Looper.java:238)
	at android.os.Looper.loop(Looper.java:357)
	at android.app.ActivityThread.main(ActivityThread.java:8090)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)

User actions: 
2022-09-07 19:45:41: MainActivity created
2022-09-07 19:45:41: MainActivity resumed
11.0.01.10.0	osgi.ee; osgi.ee="OSGi/Minimum"; version:List<Version>="1.0, 1.1, 1.2", osgi.ee; osgi.ee="JRE"; version:List<Version>="1.0, 1.1", osgi.ee; osgi.ee="JavaSE"; version:List<Version>="1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 9.0, 10.0, 11.0",osgi.ee; osgi.ee="JavaSE/compact1"; version:List<Version>="1.8, 9.0, 10.0, 11.0",osgi.ee; osgi.ee="JavaSE/compact2"; version:List<Version>="1.8, 9.0, 10.0, 11.0",osgi.ee; osgi.ee="JavaSE/compact3"; version:List<Version>="1.8, 9.0, 10.0, 11.0", eclipse.platform; osgi.os=win32; osgi.ws=win32; osgi.arch=x86_64; osgi.nl=en_PH, osgi.native; osgi.native.osname:List<String>="Windows10,Windows 10,Win10,Win32"; osgi.native.processor:List<String>="x86-64,amd64,em64t,x86_64"; osgi.native.osversion:Version="10.0.0"; osgi.native.language="en"icom.jetbrains.management, com.sun.jarsigner, com.sun.java.accessibility.util, com.sun.javadoc, com.sun.jdi, com.sun.jdi.connect, com.sun.jdi.connect.spi, com.sun.jdi.event, com.sun.jdi.request, com.sun.management, com.sun.net.httpserver, com.sun.net.httpserver.spi, com.sun.nio.file, com.sun.nio.sctp, com.sun.security.auth, com.sun.security.auth.callback, com.sun.security.auth.login, com.sun.security.auth.module, com.sun.security.jgss, com.sun.source.doctree, com.sun.source.tree, com.sun.source.util, com.sun.tools.attach, com.sun.tools.attach.spi, com.sun.tools.javac, com.sun.tools.javadoc, java.applet, java.awt, java.awt.color, java.awt.datatransfer, java.awt.desktop, java.awt.dnd, java.awt.event, java.awt.font, java.awt.geom, java.awt.im, java.awt.im.spi, java.awt.image, java.awt.image.renderable, java.awt.print, java.beans, java.beans.beancontext, java.io, java.lang, java.lang.annotation, java.lang.instrument, java.lang.invoke, java.lang.management, java.lang.module, java.lang.ref, java.lang.reflect, java.math, java.net, java.net.http, java.net.spi, java.nio, java.nio.channels, java.nio.channels.spi, java.nio.charset, java.nio.charset.spi, java.nio.file, java.nio.file.attribute, java.nio.file.spi, java.rmi, java.rmi.activation, java.rmi.dgc, java.rmi.registry, java.rmi.server, java.security, java.security.acl, java.security.cert, java.security.interfaces, java.security.spec, java.sql, java.text, java.text.spi, java.time, java.time.chrono, java.time.format, java.time.temporal, java.time.zone, java.util, java.util.concurrent, java.util.concurrent.atomic, java.util.concurrent.locks, java.util.function, java.util.jar, java.util.logging, java.util.prefs, java.util.regex, java.util.spi, java.util.stream, java.util.zip, javax.accessibility, javax.annotation.processing, javax.crypto, javax.crypto.interfaces, javax.crypto.spec, javax.imageio, javax.imageio.event, javax.imageio.metadata, javax.imageio.plugins.bmp, javax.imageio.plugins.jpeg, javax.imageio.plugins.tiff, javax.imageio.spi, javax.imageio.stream, javax.lang.model, javax.lang.model.element, javax.lang.model.type, javax.lang.model.util, javax.management, javax.management.loading, javax.management.modelmbean, javax.management.monitor, javax.management.openmbean, javax.management.relation, javax.management.remote, javax.management.remote.rmi, javax.management.timer, javax.naming, javax.naming.directory, javax.naming.event, javax.naming.ldap, javax.naming.spi, javax.net, javax.net.ssl, javax.print, javax.print.attribute, javax.print.attribute.standard, javax.print.event, javax.rmi.ssl, javax.script, javax.security.auth, javax.security.auth.callback, javax.security.auth.kerberos, javax.security.auth.login, javax.security.auth.spi, javax.security.auth.x500, javax.security.cert, javax.security.sasl, javax.smartcardio, javax.sound.midi, javax.sound.midi.spi, javax.sound.sampled, javax.sound.sampled.spi, javax.sql, javax.sql.rowset, javax.sql.rowset.serial, javax.sql.rowset.spi, javax.swing, javax.swing.border, javax.swing.colorchooser, javax.swing.event, javax.swing.filechooser, javax.swing.plaf, javax.swing.plaf.basic, javax.swing.plaf.metal, javax.swing.plaf.multi, javax.swing.plaf.nimbus, javax.swing.plaf.synth, javax.swing.table, javax.swing.text, javax.swing.text.html, javax.swing.text.html.parser, javax.swing.text.rtf, javax.swing.tree, javax.swing.undo, javax.tools, javax.transaction.xa, javax.xml, javax.xml.catalog, javax.xml.crypto, javax.xml.crypto.dom, javax.xml.crypto.dsig, javax.xml.crypto.dsig.dom, javax.xml.crypto.dsig.keyinfo, javax.xml.crypto.dsig.spec, javax.xml.datatype, javax.xml.namespace, javax.xml.parsers, javax.xml.stream, javax.xml.stream.events, javax.xml.stream.util, javax.xml.transform, javax.xml.transform.dom, javax.xml.transform.sax, javax.xml.transform.stax, javax.xml.transform.stream, javax.xml.validation, javax.xml.xpath, jdk.dynalink, jdk.dynalink.beans, jdk.dynalink.linker, jdk.dynalink.linker.support, jdk.dynalink.support, jdk.javadoc.doclet, jdk.jfr, jdk.jfr.consumer, jdk.management.jfr, jdk.nashorn.api.scripting, jdk.nashorn.api.tree, jdk.net, jdk.nio, jdk.security.jarsigner, netscape.javascript, org.ietf.jgss, org.w3c.dom, org.w3c.dom.bootstrap, org.w3c.dom.css, org.w3c.dom.events, org.w3c.dom.html, org.w3c.dom.ls, org.w3c.dom.ranges, org.w3c.dom.stylesheets, org.w3c.dom.traversal, org.w3c.dom.views, org.w3c.dom.xpath, org.xml.sax, org.xml.sax.ext, org.xml.sax.helpers, sun.misc, sun.reflectBundle-SymbolicNameBundle-ActivationPolicyService-Component System Bundle�v�0!org.eclipse.osgi; singleton:=true����;org.eclipse.osgi.internal.connect.ConnectHookConfigurator$1�ҝx@�ҝx@java.appletorg.osgi.service.log.LogServicejava.awt.imagejavax.xml.crypto.dsig.domjavax.xml.stream 
 x-internaljavax.swing.tablejava.awt.desktopjavax.imageio.plugins.jpeg	javax.lang.model.type 
 .org.eclipse.osgi.internal.provisional.verifierjava.security.cert java.util.zip javax.xml.transform.dom java.nio.fileem64torg.w3c.dom.views#org.eclipse.osgi.container.builders osgi.identity	java.time!org.osgi.framework.hooks.resolverjavax.security.auth.callbackjavax.xml.stream.utiljavax.lang.model.element%org.eclipse.osgi.service.localizationorg.w3c.dom.bootstrap+org.eclipse.osgi.service.debug.DebugOptionscom.sun.nio.sctpWin10javax.xml.validationosgi.ee#org.eclipse.osgi.framework.eventmgr jdk.dynalink.beans! javax.imageio"javax.swing.text#com.sun.jarsigner$version%com.sun.net.httpserver&com.sun.jdi.connect'org.osgi.framework(org.w3c.dom.events)java.awt.datatransfer*javax.swing.plaf+javax.swing.text.html,com.sun.jdi.event-jdk.dynalink.javax.swing.plaf.metal/java.net.spi0java.rmi.activation1org.osgi.framework.dto2java.util.logging3javax.swing.colorchooser4	javax.xml5bundle-symbolic-name6)org.eclipse.osgi.internal.serviceregistry7%org.eclipse.osgi.service.datalocation8jdk.dynalink.support9javax.security.auth.x500:&org.osgi.service.log.admin.LoggerAdmin;java.util.stream<javax.lang.model=java.lang.annotation>jdk.jfr?javax.imageio.spi@org.eclipse.osgi.signedcontentAorg.osgi.service.log.adminBorg.osgi.framework.connectCjavax.naming.directoryDjava.time.chronoEjavax.management.loadingFjavax.security.authG-org.eclipse.osgi.service.security.TrustEngineH%org.osgi.service.log.LogReaderServiceI	java.mathJorg.eclipse.osgi.internal.debugKO(| (&(osgi.ee=JavaSE)(version=1.8)) (&(osgi.ee=JavaSE/compact1)(version=1.8)) )Lorg.w3c.domM java.awt.geomNjavax.transaction.xaO!org.eclipse.osgi.service.resolverPjavax.xml.transform.staxQ9org.eclipse.osgi.internal.framework.SystemBundleActivatorRorg.w3c.dom.traversalSv20220215-2237Tjava.awtU3org.eclipse.osgi.signedcontent.SignedContentFactoryVorg.eclipse.core.runtimeW org.eclipse.osgi.internal.loaderX	java.textY%org.eclipse.osgi.container.namespacesZcom.sun.management[javax.swing.undo\javax.xml.transform.stream]javax.xml.datatype^javax.print_information`Gorg.osgi.framework,org.osgi.framework.launch,org.osgi.framework.connectajavax.security.auth.loginborg.w3c.dom.htmlc#org.eclipse.osgi.storage.bundlefiledcom.sun.security.auth.logine&org.eclipse.osgi.storage.url.referencefjava.rmig0org.eclipse.equinox.log.ExtendedLogReaderServicehorg.eclipse.osgiicom.sun.jdi.connect.spij 
 java.beansk	javax.sqlljavax.print.eventmen_PHnosgi.wiring.hosto$org.osgi.framework,org.osgi.resourcepjava.util.prefsqjavax.imageio.metadatarNorg.osgi.framework,org.osgi.framework.hooks.resolver,org.osgi.framework.wiringsjava.nettosgi.nativeu.org.eclipse.osgi.service.datalocation.Locationvorg.osgi.service.condpermadminwjavax.naming.spix*org.osgi.service.packageadmin.PackageAdminyjavax.imageio.plugins.bmpzsun.misc{java.time.format|jdk.nashorn.api.scripting}3org.eclipse.osgi.service.urlconversion.URLConverter~java.util.concurrent+org.eclipse.osgi.framework.log.FrameworkLog�en�javax.security.auth.spi�*org.eclipse.osgi.internal.service.security�java.rmi.server�javax.sound.sampled�javax.sql.rowset.serial�javax.xml.parsers�org.osgi.service.url�javax.swing.plaf.synth�org.eclipse.osgi.util�org.osgi.service.resolver�osgi.wiring.package�javax.swing.plaf.basic�org.osgi.resource.dto�javax.swing.tree�!org.eclipse.osgi.service.security�java.util.function�	javax.net�java.awt.image.renderable�jdk.dynalink.linker�com.sun.nio.file�org.w3c.dom.ls�javax.smartcardio�javax.naming�jdk.dynalink.linker.support�'org.osgi.framework,org.osgi.service.log�org.osgi.framework.namespace�java.rmi.dgc�#org.eclipse.osgi.internal.framework�"org.eclipse.osgi.framework.console�!org.osgi.framework.startlevel.dto�javax.xml.xpath�javax.annotation.processing�&org.osgi.service.startlevel.StartLevel�8org.eclipse.osgi.service.localization.BundleLocalization�osgi.wiring.bundle�osgi.native.osname� java.net.http�org.osgi.resource�java.lang.invoke�org.osgi.service.log� org.osgi.framework.hooks.service�javax.security.cert�	singleton�org.w3c.dom.xpath�osgi.os�javax.xml.catalog�jdk.nio�org.eclipse.osgi.launch�&org.eclipse.osgi.service.urlconversion�org.osgi.framework.wiring�java.lang.management�JavaSE/compact1�org.osgi.dto�JavaSE/compact2�JavaSE/compact3�java.util.concurrent.atomic�osgi.instance.area� javax.rmi.ssl�javax.swing.event�"org.osgi.service.resolver.Resolver�java.awt.color�javax.management.openmbean�javax.swing.text.rtf� System Bundle�jdk.javadoc.doclet�java.awt.print�javax.xml.crypto�javax.swing.plaf.multi�java.nio.channels.spi�javax.imageio.event� org.osgi.service.permissionadmin� javax.net.ssl�$org.eclipse.osgi.service.environment�java.rmi.registry�javax.xml.stream.events�com.sun.java.accessibility.util�javax.print.attribute�equinox.module.data�java.nio.file.attribute�javax.swing�org.osgi.framework.launch�jdk.management.jfr�com.sun.tools.javadoc�java.nio�4org.eclipse.osgi.service.environment.EnvironmentInfo�osgi.nl�type�com.sun.jdi.request�org.eclipse.osgi.report.resolution, org.osgi.framework.wiring, org.eclipse.osgi.framework.eventmgr, org.osgi.framework.startlevel, org.osgi.framework, org.osgi.framework.hooks.resolver, org.osgi.service.resolver, org.osgi.resource, org.eclipse.osgi.service.debug�"org.eclipse.osgi.internal.messages�java.lang.instrument� java.lang.ref�java.util.regex�org.eclipse.osgi.tests� org.ietf.jgss�eclipse.platform�javax.sound.midi.spi�javax.swing.filechooser�org.eclipse.osgi.service.debug�javax.xml.crypto.dsig.spec� 
 Windows 10�java.lang.reflect� java.security�org.xml.sax.helpers�com.sun.tools.attach�*org.eclipse.equinox.log.ExtendedLogService�javax.print.attribute.standard�	osgi.arch�+org.osgi.service.resolver,org.osgi.resource�objectClass�com.sun.javadoc�org.osgi.util.tracker�	java.lang�&org.eclipse.osgi.internal.loader.buddy�jdk.security.jarsigner�com.sun.security.auth�	activator�javax.security.auth.kerberos�java.sql�javax.crypto�	Windows10�	java.util�&org.eclipse.osgi.internal.hookregistry�java.security.acl�java.nio.channels�java.time.temporal�9org.osgi.service.condpermadmin.ConditionalPermissionAdminorg.w3c.dom.stylesheetsjava.nio.charsetjavax.sound.midi0org.eclipse.osgi.framework.internal.reliablefilejdk.netjavax.imageio.streamjavax.management.monitororg.xml.sax org.eclipse.core.runtime.adaptor	org.eclipse.osgi.container 
 com.sun.source.doctreeorg.eclipse.equinox.log(org.eclipse.osgi.internal.loader.sources com.sun.net.httpserver.spieclipse.home.locationjava.awt.dnd!org.eclipse.osgi.service.runnableorg.eclipse.osgi.storagemanagerorg.osgi.framework.startleveljava.awt.imjavax.swing.text.html.parser org.osgi.framework.hooks.weavingjavax.xml.transformorg.osgi.service.packageadminfilterorg.eclipse.osgi.internal.urlorg.w3c.dom.css0org.osgi.service.permissionadmin.PermissionAdminbundle-versionjavax.xml.crypto.dsigcom.sun.tools.javaccom.sun.jdi com.sun.security.jgss!java.nio.charset.spi"org.osgi.service.startlevel#osgi.native.language$ java.text.spi% java.util.spi&win32'javax.management.timer(x86-64)org.osgi.framework.wiring.dto*java.security.spec+java.nio.file.spi,javax.xml.crypto.dsig.keyinfo-javax.accessibility.org.eclipse.osgi.storage/com.sun.source.tree0javax.xml.namespace1osgi.native.osversion2 java.awt.font3osgi.service4java.security.interfaces5com.sun.tools.attach.spi6"org.eclipse.osgi.internal.location7org.eclipse.osgi.framework.util8javax.management.relation9javax.management.modelmbean:javax.sound.sampled.spi;	x-friends<javax.xml.transform.sax=osgi.install.area>javax.management.remote.rmi?osgi.user.area@osgi.native.processorA)org.eclipse.core.runtime.internal.adaptorBjavax.naming.eventCOSGi/MinimumDjava.util.concurrent.locksEcom.jetbrains.managementFjavax.swing.plaf.nimbusGjava.awt.eventHtrueIjavax.sql.rowset.spiJjavax.swing.borderKjdk.jfr.consumerLjavax.imageio.plugins.tiffMjavax.management.remoteNorg.xml.sax.extOJavaSEP)org.eclipse.osgi.service.pluginconversionQsun.reflectR"org.osgi.service.log.LoggerFactoryS6org.eclipse.osgi.internal.provisional.service.securityTjavax.lang.model.utilUorg.osgi.service.conditionV"org.osgi.dto,org.osgi.resource.dtoWcom.sun.security.auth.callbackX'org.eclipse.osgi.internal.signedcontentYjavax.security.saslZ	effective[0org.eclipse.osgi.util,org.eclipse.osgi.container\x86_64]com.sun.security.auth.module^ system.bundle_javax.naming.ldap`javax.xml.crypto.domajava.time.zonebjdk.nashorn.api.treecosgi.configuration.areadnetscape.javascriptejava.awt.im.spifWin32gjava.beans.beancontexthosgi.bundlei"org.eclipse.osgi.report.resolutionjjavax.managementkjavax.toolslosgi.wsmjavax.crypto.specnjavax.scriptoorg.eclipse.osgi.framework.logpjava.lang.moduleqcom.sun.source.utilrCorg.eclipse.ui.workbench,org.eclipse.equinox.p2.artifact.repositorys*org.eclipse.osgi.internal.loader.classpathtjava.ioujavax.sql.rowsetv java.util.jarwjavax.crypto.interfacesxusesyorg.eclipse.equinox.security.uizorg.w3c.dom.ranges{JRE|org.osgi.framework.hooks.bundle}amd64~	 
 ���T���������������� 
 �h�6i_�%�{����6i_�%�Q�6i_�%�(�6i_�%�u��%����6i_�%���6i_�%���6i_�%�5�6i_�%�]��%�����%����6i_�%�r�6i_�%���6i_�%�x�6i_�%�n�6i_�%� �6i_�%��Z�6i_�%�	�6i_�%�U�y\�6i_�%��Q�6i_�%��6i_�%���6i_�%�b�6i_�%�^�6i_�%�=�6i_�%�`�6i_�%�Y�6i_�%�N�6i_�%����6i_�%�J�6i_�%�@�6i_�%�=�yW�6i_�%�����6i_�%�O�6i_�%�+�6i_�%��p�6i_�%�K�6i_�%�G�6i_�%����6i_�%���6i_�%��6i_�%�,�6i_�%���6i_�%���6i_�%�Z�6i_�%�E�6i_�%�)��y�6i_�%����6i_�%�M�<s�<z�6i_�%�c�6i_�%�F�6i_�%�:�6i_�%�-�6i_�%���6i_�%���6i_�%��*�6i_�%��6i_�%����~��v��6i_�%�/�6i_�%��#�6i_�%���6i_�%�7�6i_�%�8�6i_�%�.�6i_�%��6i_�%����6i_�%�w�6i_�%�9�6i_�%��6i_�%� 
 �6i_�%�t�6i_�%���6i_�%� �6i_�%��6i_�%�1�6i_�%�-�6i_�%�H�6i_�%���6i_�%��6i_�%�� 
 �6i_�%�l�6i_�%�_�y#�y�6i_�%�K�6i_�%�h�6i_�%����6i_�%�q�6i_�%���6i_�%�d�6i_�%���6i_�%���6i_�%�D�i�i%���v�@��v�>�6i_�%��(�6i_�%�O�6i_�%���6i_�%�X��i_6i_�%�J6i_�%�k6i_�%�c6i_�%��}<�6i_�%��6i_�%�>6i_�%�F	6i_�%�4 
 6i_�%�96i_�%��6i_�%�� 6i_�%�16i_�%�	6i_�%�?6i_�%�/6i_�%�j6i_�%�"6i_�%�*6i_�%�G6i_�%��w6i_�%�76i_�%�36i_�%�56i_�%��y�6i_�%�L6i_�%�+6i_�%�#6i_�%��� 6i_�%���!6i_�%�!"6i_�%��T#6i_�%���$6i_�%�%6i_�%�z&6i_�%�''6i_�%�N(y�)6i_�%�0*6i_�%�+6i_�%�,6i_�%�-6i_�%�.6i_�%�r/6i_�%�� 06i_�%�q16i_�%�b2y�36i_�%�v46i_�%�35�v�d6�'m'�n�]7y�86i_�%�96i_�%��:6i_�%�Y;6i_�%�.<6i_�%�=6i_�%�%>y�?6i_�%��@6i_�%�eA6i_�%��B6i_�%��Cy�D6i_�%��E6i_�%��F6i_�%��G6i_�%�[H6i_�%��I6i_�%�UJ6i_�%��K6i_�%�L6i_�%��M6i_�%�SNLO6i_�%���P6i_�%��Q6i_�%��R6i_�%���S�HT6i_�%��U6i_�%�^V6i_�%��AW6i_�%��X6i_�%�EYy�Z6i_�%��[6i_�%��\6i_�%�\]6i_�%���^6i_�%�M_y�`y�ay�by�c6i_�%��2d6i_�%��e6i_�%���f6i_�%�g6i_�%��h6i_�%�i6i_�%�:j6i_�%�k6i_�%��l6i_�%��m6i_�%��ny�o6i_�%��p6i_�%�q6i_�%�r6i_�%��s6i_�%��t6i_�%�<u6i_�%���v6i_�%��Cw6i_�%�x6i_�%��y6i_�%��Bz6i_�%�&{y�|6i_�%��}6i_�%��~6i_�%�6i_�%���;�6i_�%���y��6i_�%�|�6i_�%���6i_�%���6i_�%���|%���6i_�%�$�6i_�%����R��oi_��I�6i_�%���6i_�%���6i_�%��8�6i_�%����6i_�%��6i_�%��6i_�%��6i_�%��6i_�%���P%������������6i_�%���6i_�%���6i_�%����ys�6i_�%����6i_�%�t�yw�yp�6i_�%�m�6i_�%�l�6i_�%�{��V�6i_�%�g�6i_�%�k�6i_�%����S��6i_�%�"�ya�6i_�%� �6i_�%�R�6i_�%��6i_�%��6i_�%���6i_�%���6i_�%�o�6i_�%���6i_�%��6i_�%��6i_�%����Ih�6i_�%��6i_�%��6i_�%������6i_�%���6i_�%����6i_�%����6i_�%���6i_�%��6i_�%�0�6i_�%�a�[`�6i_�%��6i_�%�f�6i_�%�e����6i_�%����6i_�%���6i_�%���yB�yA�6i_�%���6i_�%�X���D%����6i_�%���6i_�%���y8�6i_�%���I�6i_�%���6i_�%�C�6i_�%�B�6i_�%���6i_�%���y(�6i_�%���6i_�%���<W�6i_�%����6i_�%�x�6i_�%��V�6i_�%�����6i_�%���6i_�%���6i_�%�;�6i_�%�&�6i_�%�?�6i_�%�����y�6i_�%���6i_�%���6i_�%���6i_�%�,�6i_�%�6�6i_�%��j�6i_�%�}�6i_�%���6i_�%���6i_�%�!�6i_�%����y�A)~]2����g$��6i_�%��P�6i_�%�f�6i_�%����v�����i�C����o��������������o��3�:���b����0�������	��� 
 �������� ������������������#��������������������������!������� ���!���"���#�v�$�W�%��&���'���(���)�^�*���+���,�w8-�dZ.��/�C`0�f�1��`2���3��b4���5�PZ6���7���8���9��Z:���;��<���=�zc>���?�S�@��bA���B�$�C���D���E���F�l�G���H���I�'�J��K���L���M�H�N�{�O���P�y�Q���R���S���T�A�U���V���W���X�*�Y���Z���[���\�q�]���^���_�J�`���a��b�-�c���d���e�5�f�(�g���h���i���j���k�M�l���m���n���o���p��q���r���s�X�t���u���v���w��x���y���z���{���|�m�}�F�~�k������=���������������������Q���������������.���������������;���>�������Y�������������������������������n����������1�����������u�����������[������������������E���/���&��������������g����������������������	�������������������������������p�������������������~���B�������@�����������U����������+�������2���e���j�����������s�����������������������4������������������� 
 ���R�����������������G��������������������������\���}���]��������������K���I����������������������V��������������h�����������9��������������������<��"�� ��t�������	�� 
 ��������� �i��������������_��%��L�������������x��N��,�����r������� ���!���"4�c#4�c$4��%4��&4��'4��(46�)4��*4��+4�D,4��-4��.4�?/4��04��14 )24�a34��44T|54��6��7��8��9��:��;��<�7�=u��>���?�O�ҝxq@8�?��B����	 
 !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~��������������������������������������������������������������������������������������������������������������������������������	 
 !"#$%&'()*+,-./0123456789:;<=?@@plugins { 
     id 'com.android.library' 
 } 
  
 android { 
     compileSdkVersion rootProject.ext.compileSdkVersion 
     buildToolsVersion rootProject.ext.buildToolsVersion 
  
     defaultConfig { 
         minSdk 21 
         targetSdk 32 
  
         testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner" 
         consumerProguardFiles "consumer-rules.pro" 
     } 
  
     buildTypes { 
         release { 
             minifyEnabled false 
             proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro' 
         } 
     } 
     compileOptions { 
         sourceCompatibility JavaVersion.VERSION_1_8 
         targetCompatibility JavaVersion.VERSION_1_8 
     } 
 } 
  
 dependencies { 
  
     api 'me.xdrop:fuzzywuzzy:1.3.1' 
     api project(path: ':build-tools:project') 
  
     implementation project(path: ':editor-api') 
     implementation project(path: ':common') 
     implementation project(path: ':language-api') 
  
     testImplementation 'junit:junit:4.+' 
     androidTestImplementation 'androidx.test.ext:junit:1.1.3' 
     androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0' 
 }name: Android Tests CI 
  
 on: 
   workflow_dispatch: 
   push: 
     branches: [ javac-17 ] 
   pull_request: 
     branches: [ javac-17 ] 
  
 jobs: 
   build: 
  
     runs-on: ubuntu-latest 
  
     steps: 
     - uses: actions/checkout@v2 
     - name: set up JDK 11 
       uses: actions/setup-java@v2 
       with: 
         java-version: '11' 
         distribution: 'adopt' 
         cache: gradle 
  
     - name: Grant execute permission for gradlew 
       run: chmod +x gradlew 
     - name: Build with Gradle 
       run: ./gradlew test
stderr:

/box/script.js:1 name: Android CI ^^ SyntaxError: Unexpected identifier at Module._compile (internal/modules/cjs/loader.js:895:18) at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10) at Module.load (internal/modules/cjs/loader.js:815:32) at Function.Module._load (internal/modules/cjs/loader.js:727:14) at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) at internal/main/run_main_module.js:17:11 172.58.39.254motorola/denver_global/denver:11/RRES31.Q3-60-47-2-2-2/c170ed:user/acb1c744-790c-4286-b8ec-4b44121338644412133864d933765d03c83d50ce:58:f0:5a:3c:ff64:11:a4:c7:17:0ed2:95:c2:fb:c7:5e192.168.12.210

**Comment by Erikjjkkkjj** [comment]
Lsls
