### ISSUE TITLE
Kotlin

### ISSUE THREAD

**Issue by TimScriptov** [tyron12233/CodeAssist#49]
2021-12-12 15:33:16.566 15817-15941/com.tyron.code E/AndroidRuntime: FATAL EXCEPTION: pool-12-thread-1
    Process: com.tyron.code, PID: 15817
    java.lang.Error: java.lang.NoSuchMethodException: getAndAddInt [class java.lang.Object, long, int]
        at org.jetbrains.kotlin.com.intellij.util.containers.ConcurrentIntObjectHashMap.<clinit>(ConcurrentIntObjectHashMap.java:2809)
        at org.jetbrains.kotlin.com.intellij.util.containers.ContainerUtil.createConcurrentIntObjectMap(ContainerUtil.java:2593)
        at org.jetbrains.kotlin.com.intellij.util.io.StorageLock.<init>(StorageLock.java:73)
        at org.jetbrains.kotlin.com.intellij.util.io.PagedFileStorage.<clinit>(PagedFileStorage.java:26)
        at org.jetbrains.kotlin.com.intellij.util.io.ResizeableMappedFile.<init>(ResizeableMappedFile.java:59)
        at org.jetbrains.kotlin.com.intellij.util.io.PersistentBTreeEnumerator.<init>(PersistentBTreeEnumerator.java:73)
        at org.jetbrains.kotlin.com.intellij.util.io.PersistentEnumeratorDelegate.createDefaultEnumerator(PersistentEnumeratorDelegate.java:69)
        at org.jetbrains.kotlin.com.intellij.util.io.PersistentHashMap.<init>(PersistentHashMap.java:164)
        at org.jetbrains.kotlin.com.intellij.util.io.PersistentHashMap.<init>(PersistentHashMap.java:149)
        at org.jetbrains.kotlin.com.intellij.util.io.PersistentHashMap.<init>(PersistentHashMap.java:140)
        at org.jetbrains.kotlin.com.intellij.util.io.PersistentHashMap.<init>(PersistentHashMap.java:132)
        at org.jetbrains.kotlin.com.intellij.util.io.PersistentHashMap.<init>(PersistentHashMap.java:119)
        at org.jetbrains.kotlin.incremental.storage.CachingLazyStorage.createMap(CachingLazyStorage.kt:120)
        at org.jetbrains.kotlin.incremental.storage.CachingLazyStorage.getStorageOrCreateNew(CachingLazyStorage.kt:54)
        at org.jetbrains.kotlin.incremental.storage.CachingLazyStorage.set(CachingLazyStorage.kt:73)
        at org.jetbrains.kotlin.incremental.snapshots.FileSnapshotMap.compareAndUpdate(FileSnapshotMap.kt:55)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl(IncrementalCompilerRunner.kt:133)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:80)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile$default(IncrementalCompilerRunner.kt:71)
        at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunnerKt.makeIncrementally(IncrementalJvmCompilerRunner.kt:94)
        at com.tyron.builder.compiler.incremental.kotlin.IncrementalKotlinCompiler.run(IncrementalKotlinCompiler.java:114)
        at com.tyron.builder.compiler.BuilderImpl.build(BuilderImpl.java:59)
        at com.tyron.code.service.CompilerService.lambda$compile$4$com-tyron-code-service-CompilerService(CompilerService.java:175)
        at com.tyron.code.service.CompilerService$$ExternalSyntheticLambda3.run(Unknown Source:6)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
     Caused by: java.lang.NoSuchMethodException: getAndAddInt [class java.lang.Object, long, int]
        at java.lang.invoke.MethodHandles$Lookup.findVirtual(MethodHandles.java:923)
        at org.jetbrains.kotlin.com.intellij.util.containers.ConcurrentIntObjectHashMap.<clinit>(ConcurrentIntObjectHashMap.java:2805)
        at org.jetbrains.kotlin.com.intellij.util.containers.ContainerUtil.createConcurrentIntObjectMap(ContainerUtil.java:2593) 
        at org.jetbrains.kotlin.com.intellij.util.io.StorageLock.<init>(StorageLock.java:73) 
        at org.jetbrains.kotlin.com.intellij.util.io.PagedFileStorage.<clinit>(PagedFileStorage.java:26) 
        at org.jetbrains.kotlin.com.intellij.util.io.ResizeableMappedFile.<init>(ResizeableMappedFile.java:59) 
        at org.jetbrains.kotlin.com.intellij.util.io.PersistentBTreeEnumerator.<init>(PersistentBTreeEnumerator.java:73) 
        at org.jetbrains.kotlin.com.intellij.util.io.PersistentEnumeratorDelegate.createDefaultEnumerator(PersistentEnumeratorDelegate.java:69) 
        at org.jetbrains.kotlin.com.intellij.util.io.PersistentHashMap.<init>(PersistentHashMap.java:164) 
        at org.jetbrains.kotlin.com.intellij.util.io.PersistentHashMap.<init>(PersistentHashMap.java:149) 
        at org.jetbrains.kotlin.com.intellij.util.io.PersistentHashMap.<init>(PersistentHashMap.java:140) 
        at org.jetbrains.kotlin.com.intellij.util.io.PersistentHashMap.<init>(PersistentHashMap.java:132) 
        at org.jetbrains.kotlin.com.intellij.util.io.PersistentHashMap.<init>(PersistentHashMap.java:119) 
        at org.jetbrains.kotlin.incremental.storage.CachingLazyStorage.createMap(CachingLazyStorage.kt:120) 
        at org.jetbrains.kotlin.incremental.storage.CachingLazyStorage.getStorageOrCreateNew(CachingLazyStorage.kt:54) 
        at org.jetbrains.kotlin.incremental.storage.CachingLazyStorage.set(CachingLazyStorage.kt:73) 
        at org.jetbrains.kotlin.incremental.snapshots.FileSnapshotMap.compareAndUpdate(FileSnapshotMap.kt:55) 
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl(IncrementalCompilerRunner.kt:133) 
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:80) 
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile$default(IncrementalCompilerRunner.kt:71) 
        at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunnerKt.makeIncrementally(IncrementalJvmCompilerRunner.kt:94) 
        at com.tyron.builder.compiler.incremental.kotlin.IncrementalKotlinCompiler.run(IncrementalKotlinCompiler.java:114) 
        at com.tyron.builder.compiler.BuilderImpl.build(BuilderImpl.java:59) 
        at com.tyron.code.service.CompilerService.lambda$compile$4$com-tyron-code-service-CompilerService(CompilerService.java:175) 
        at com.tyron.code.service.CompilerService$$ExternalSyntheticLambda3.run(Unknown Source:6) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:920) 
2021-12-12 15:33:16.569 15817-15941/com.tyron.code E/CrashActivity: App has crashed, executing CrashActivity's UncaughtExceptionHandler
    java.lang.Error: java.lang.NoSuchMethodException: getAndAddInt [class java.lang.Object, long, int]
        at org.jetbrains.kotlin.com.intellij.util.containers.ConcurrentIntObjectHashMap.<clinit>(ConcurrentIntObjectHashMap.java:2809)
        at org.jetbrains.kotlin.com.intellij.util.containers.ContainerUtil.createConcurrentIntObjectMap(ContainerUtil.java:2593)
        at org.jetbrains.kotlin.com.intellij.util.io.StorageLock.<init>(StorageLock.java:73)
        at org.jetbrains.kotlin.com.intellij.util.io.PagedFileStorage.<clinit>(PagedFileStorage.java:26)
        at org.jetbrains.kotlin.com.intellij.util.io.ResizeableMappedFile.<init>(ResizeableMappedFile.java:59)
        at org.jetbrains.kotlin.com.intellij.util.io.PersistentBTreeEnumerator.<init>(PersistentBTreeEnumerator.java:73)
        at org.jetbrains.kotlin.com.intellij.util.io.PersistentEnumeratorDelegate.createDefaultEnumerator(PersistentEnumeratorDelegate.java:69)
        at org.jetbrains.kotlin.com.intellij.util.io.PersistentHashMap.<init>(PersistentHashMap.java:164)
        at org.jetbrains.kotlin.com.intellij.util.io.PersistentHashMap.<init>(PersistentHashMap.java:149)
        at org.jetbrains.kotlin.com.intellij.util.io.PersistentHashMap.<init>(PersistentHashMap.java:140)
        at org.jetbrains.kotlin.com.intellij.util.io.PersistentHashMap.<init>(PersistentHashMap.java:132)
        at org.jetbrains.kotlin.com.intellij.util.io.PersistentHashMap.<init>(PersistentHashMap.java:119)
        at org.jetbrains.kotlin.incremental.storage.CachingLazyStorage.createMap(CachingLazyStorage.kt:120)
        at org.jetbrains.kotlin.incremental.storage.CachingLazyStorage.getStorageOrCreateNew(CachingLazyStorage.kt:54)
        at org.jetbrains.kotlin.incremental.storage.CachingLazyStorage.set(CachingLazyStorage.kt:73)
        at org.jetbrains.kotlin.incremental.snapshots.FileSnapshotMap.compareAndUpdate(FileSnapshotMap.kt:55)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl(IncrementalCompilerRunner.kt:133)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:80)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile$default(IncrementalCompilerRunner.kt:71)
        at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunnerKt.makeIncrementally(IncrementalJvmCompilerRunner.kt:94)
        at com.tyron.builder.compiler.incremental.kotlin.IncrementalKotlinCompiler.run(IncrementalKotlinCompiler.java:114)
        at com.tyron.builder.compiler.BuilderImpl.build(BuilderImpl.java:59)
        at com.tyron.code.service.CompilerService.lambda$compile$4$com-tyron-code-service-CompilerService(CompilerService.java:175)
        at com.tyron.code.service.CompilerService$$ExternalSyntheticLambda3.run(Unknown Source:6)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
     Caused by: java.lang.NoSuchMethodException: getAndAddInt [class java.lang.Object, long, int]
        at java.lang.invoke.MethodHandles$Lookup.findVirtual(MethodHandles.java:923)
        at org.jetbrains.kotlin.com.intellij.util.containers.ConcurrentIntObjectHashMap.<clinit>(ConcurrentIntObjectHashMap.java:2805)
        at org.jetbrains.kotlin.com.intellij.util.containers.ContainerUtil.createConcurrentIntObjectMap(ContainerUtil.java:2593) 
        at org.jetbrains.kotlin.com.intellij.util.io.StorageLock.<init>(StorageLock.java:73) 
        at org.jetbrains.kotlin.com.intellij.util.io.PagedFileStorage.<clinit>(PagedFileStorage.java:26) 
        at org.jetbrains.kotlin.com.intellij.util.io.ResizeableMappedFile.<init>(ResizeableMappedFile.java:59) 
        at org.jetbrains.kotlin.com.intellij.util.io.PersistentBTreeEnumerator.<init>(PersistentBTreeEnumerator.java:73) 
        at org.jetbrains.kotlin.com.intellij.util.io.PersistentEnumeratorDelegate.createDefaultEnumerator(PersistentEnumeratorDelegate.java:69) 
        at org.jetbrains.kotlin.com.intellij.util.io.PersistentHashMap.<init>(PersistentHashMap.java:164) 
        at org.jetbrains.kotlin.com.intellij.util.io.PersistentHashMap.<init>(PersistentHashMap.java:149) 
        at org.jetbrains.kotlin.com.intellij.util.io.PersistentHashMap.<init>(PersistentHashMap.java:140) 
        at org.jetbrains.kotlin.com.intellij.util.io.PersistentHashMap.<init>(PersistentHashMap.java:132) 
        at org.jetbrains.kotlin.com.intellij.util.io.PersistentHashMap.<init>(PersistentHashMap.java:119) 
        at org.jetbrains.kotlin.incremental.storage.CachingLazyStorage.createMap(CachingLazyStorage.kt:120) 
        at org.jetbrains.kotlin.incremental.storage.CachingLazyStorage.getStorageOrCreateNew(CachingLazyStorage.kt:54) 
        at org.jetbrains.kotlin.incremental.storage.CachingLazyStorage.set(CachingLazyStorage.kt:73) 
        at org.jetbrains.kotlin.incremental.snapshots.FileSnapshotMap.compareAndUpdate(FileSnapshotMap.kt:55) 
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl(IncrementalCompilerRunner.kt:133) 
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:80) 
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile$default(IncrementalCompilerRunner.kt:71) 
        at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunnerKt.makeIncrementally(IncrementalJvmCompilerRunner.kt:94) 
        at com.tyron.builder.compiler.incremental.kotlin.IncrementalKotlinCompiler.run(IncrementalKotlinCompiler.java:114) 
        at com.tyron.builder.compiler.BuilderImpl.build(BuilderImpl.java:59) 
        at com.tyron.code.service.CompilerService.lambda$compile$4$com-tyron-code-service-CompilerService(CompilerService.java:175) 
        at com.tyron.code.service.CompilerService$$ExternalSyntheticLambda3.run(Unknown Source:6) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:920)

**Comment by tyron12233** [comment]
This is fixed on version [0.1.2](https://github.com/tyron12233/CodeAssist/releases/tag/ALPHA-0.1.2)

**Comment by TimScriptov** [comment]
@tyron12233 I have now compiled your source code from the MASTER branch and again got this error

**Comment by tyron12233** [comment]
Whats your android version?

**Comment by TimScriptov** [comment]
@tyron12233 Xiaomi Redmi 7
Custom AOSP firmware: Android 12

**Comment by tyron12233** [comment]
Seems like `Lsun/misc/Unsafe;->getAndAddInt(Ljava/lang/Object;JI)I` has been added to reflection restrictions in android 12

**Comment by tyron12233** [comment]
Can you check if the fix works? https://github.com/tyron12233/CodeAssist/releases/tag/ALPHA-0.1.3

**Comment by TimScriptov** [comment]
Not working

**Comment by tyron12233** [comment]
is there a new error?

**Comment by TimScriptov** [comment]
![Screenshot_20211212-221359](https://user-images.githubusercontent.com/31324315/145722427-de3c50ca-2c77-41af-bd59-e6070527b6ce.png)
![Screenshot_20211212-221404](https://user-images.githubusercontent.com/31324315/145722430-12b11a43-543e-4e1d-bd65-ef16ebf757a1.png)
![Screenshot_20211212-221417](https://user-images.githubusercontent.com/31324315/145722433-6cf545ef-1b25-42f3-abf1-ae5a20aca652.png)


Kotlin compiler - errors
Build APK - success😄

**Comment by tyron12233** [comment]
Can you check if it still occurs with https://file.io/0iq6vmpyi0xD

**Comment by TimScriptov** [comment]
> Can you check if it still occurs with https://file.io/0iq6vmpyi0xD

Good job! Thanks!

![Screenshot_20211212-231408](https://user-images.githubusercontent.com/31324315/145724424-5e49d00b-2395-438e-bd1b-5cc5e16f38b2.png)
![Screenshot_20211212-231520](https://user-images.githubusercontent.com/31324315/145724428-5782d2ce-be2a-4e17-ae20-a29a6611ffd6.png)
![Screenshot_20211212-231524](https://user-images.githubusercontent.com/31324315/145724434-fe190b91-6ce0-42cc-8666-67321844e26b.png)
