### ISSUE TITLE
Compilation crash

### ISSUE THREAD

**Issue by rdm600** [tyron12233/CodeAssist#51]
Build version: 0.1 ALPHA 
Build date: 1981-01-01 01:01:02 
Current date: 2021-12-12 22:14:34 
Device: Samsung SM-M215F 
 
Stack trace:  
java.lang.OutOfMemoryError: Failed to allocate a 80 byte allocation with 3784 free bytes and 3784B until OOM, target footprint 536870912, growth limit 536870912; failed due to fragmentation (largest possible contiguous allocation 214171648 bytes)
	at org.openjdk.tools.javac.resources.javac.getContents(Unknown Source:2292)
	at java.util.ListResourceBundle.loadLookup(ListResourceBundle.java:195)
	at java.util.ListResourceBundle.handleGetObject(ListResourceBundle.java:130)
	at java.util.ResourceBundle.getObject(ResourceBundle.java:439)
	at java.util.ResourceBundle.getString(ResourceBundle.java:405)
	at org.openjdk.tools.javac.util.JavacMessages.getLocalizedString(JavacMessages.java:195)
	at org.openjdk.tools.javac.util.JavacMessages.getLocalizedString(JavacMessages.java:147)
	at org.openjdk.tools.javac.util.JavacMessages.getLocalizedString(JavacMessages.java:140)
	at org.openjdk.tools.javac.util.Log.localize(Log.java:788)
	at org.openjdk.tools.javac.util.Log.printLines(Log.java:586)
	at org.openjdk.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:170)
	at org.openjdk.tools.javac.api.JavacTaskImpl.analyze(JavacTaskImpl.java:363)
	at com.tyron.builder.compiler.incremental.java.IncrementalJavaTask.run(IncrementalJavaTask.java:147)
	at com.tyron.builder.compiler.BuilderImpl.build(BuilderImpl.java:59)
	at com.tyron.code.service.CompilerService.lambda$compile$4$CompilerService(CompilerService.java:175)
	at com.tyron.code.service.CompilerService$$ExternalSyntheticLambda3.run(Unknown Source:6)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

User actions: 
2021-12-12 20:50:48: MainActivity created
2021-12-12 20:50:48: MainActivity resumed
2021-12-12 20:51:30: MainActivity paused
2021-12-12 20:56:08: MainActivity resumed
2021-12-12 20:56:23: MainActivity paused
2021-12-12 21:00:41: MainActivity resumed
2021-12-12 21:00:50: MainActivity paused
2021-12-12 21:00:50: SettingsActivity created
2021-12-12 21:00:50: SettingsActivity resumed
2021-12-12 21:00:56: SettingsActivity paused
2021-12-12 21:00:57: MainActivity resumed
2021-12-12 21:00:57: SettingsActivity destroyed
2021-12-12 21:01:03: MainActivity paused
2021-12-12 21:01:06: MainActivity resumed
2021-12-12 21:02:22: MainActivity paused
2021-12-12 21:02:26: MainActivity resumed
2021-12-12 21:04:03: MainActivity paused
2021-12-12 21:04:07: MainActivity resumed
2021-12-12 21:04:07: MainActivity paused
2021-12-12 21:05:02: MainActivity resumed
2021-12-12 21:05:06: MainActivity paused
2021-12-12 21:05:08: MainActivity resumed
2021-12-12 21:08:39: MainActivity paused
2021-12-12 21:09:38: MainActivity resumed
2021-12-12 21:09:45: MainActivity paused
2021-12-12 21:20:46: MainActivity resumed
2021-12-12 21:20:57: MainActivity paused
2021-12-12 21:40:43: MainActivity resumed
2021-12-12 21:40:44: MainActivity paused
2021-12-12 21:41:26: MainActivity resumed
2021-12-12 21:42:07: MainActivity paused
2021-12-12 21:42:37: MainActivity resumed
2021-12-12 21:46:26: MainActivity paused
2021-12-12 21:46:53: MainActivity resumed
2021-12-12 21:47:44: MainActivity paused
2021-12-12 21:47:52: MainActivity resumed
2021-12-12 21:48:28: MainActivity paused
2021-12-12 21:48:34: MainActivity resumed
2021-12-12 21:48:52: MainActivity paused
2021-12-12 21:49:02: MainActivity resumed
2021-12-12 21:49:17: MainActivity paused
2021-12-12 21:49:21: MainActivity resumed
2021-12-12 21:49:28: MainActivity paused
2021-12-12 21:49:31: MainActivity resumed
2021-12-12 21:49:47: MainActivity paused
2021-12-12 21:50:03: MainActivity resumed
2021-12-12 21:50:20: MainActivity paused
2021-12-12 21:50:35: MainActivity resumed
2021-12-12 21:51:04: MainActivity paused
2021-12-12 21:51:06: MainActivity resumed
2021-12-12 21:51:13: MainActivity paused
2021-12-12 21:51:16: MainActivity resumed
2021-12-12 21:53:25: MainActivity paused
2021-12-12 21:53:37: MainActivity resumed
2021-12-12 21:53:55: MainActivity paused
2021-12-12 21:54:22: MainActivity resumed
2021-12-12 21:54:29: MainActivity paused
2021-12-12 21:54:31: MainActivity resumed
2021-12-12 21:54:42: MainActivity paused
2021-12-12 21:54:46: MainActivity resumed
2021-12-12 21:54:58: MainActivity paused
2021-12-12 21:55:00: MainActivity resumed
2021-12-12 21:55:05: MainActivity paused
2021-12-12 21:55:08: MainActivity resumed
2021-12-12 21:55:14: MainActivity paused
2021-12-12 21:55:39: MainActivity resumed
2021-12-12 21:56:21: MainActivity paused
2021-12-12 21:57:01: MainActivity resumed
2021-12-12 21:57:54: MainActivity paused
2021-12-12 21:58:01: MainActivity resumed
2021-12-12 22:04:50: MainActivity paused
2021-12-12 22:05:24: MainActivity destroyed
2021-12-12 22:08:56: MainActivity created
2021-12-12 22:08:56: MainActivity resumed
2021-12-12 22:12:05: MainActivity paused
2021-12-12 22:12:12: MainActivity destroyed
2021-12-12 22:12:25: MainActivity created
2021-12-12 22:12:39: MainActivity resumed
2021-12-12 22:12:45: MainActivity paused
2021-12-12 22:12:45: MainActivity resumed
2021-12-12 22:12:45: MainActivity paused
2021-12-12 22:12:45: MainActivity destroyed
2021-12-12 22:12:45: MainActivity created
2021-12-12 22:12:46: MainActivity resumed

**Comment by tyron12233** [comment]
how big is the project and how much ram do you have?

**Comment by rdm600** [comment]
> how big is the project and how much ram do you have?

With libraries of about 32 MB, when building APK = 4 MB. Noticeably began to sign during compilation, after many changes were made to the project (a lot of code was copied, pasted, changed)

By the way, the code editor sometimes distorts words. I write public static, and it makes ppublicstatic, for example, and there are also false red underscores.

4GB RAM

**Comment by hosnifraj0** [comment]
> how big is the project and how much ram do you have?

I think his device is under **Android 8**, so Java Complitation' process will not work.

**Comment by hosnifraj0** [comment]
> > how big is the project and how much ram do you have?
> 
> With libraries of about 32 MB, when building APK = 4 MB. Noticeably began to sign during compilation, after many changes were made to the project (a lot of code was copied, pasted, changed)
> 
> By the way, the code editor sometimes distorts words. I write public static, and it makes ppublicstatic, for example, and there are also false red underscores.
> 
> 4GB RAM

Update your **Google Keyboard** to the _latest_.

**Comment by rdm600** [comment]
> > how big is the project and how much ram do you have?
> 
> I think his device is under **Android 8**, so Java Complitation' process will not work.

Actually, Android 11, and Google keyboard is my last.

**Comment by tyron12233** [comment]
This is an issue with the code editor library. Report it [here](https://github.com/Rosemoe/sora-editor/). A work around is provided in the settings. Just disable `enable keyboard suggestions`
