### ISSUE TITLE
Crash of the visual editor

### ISSUE THREAD

**Issue by rdm600** [tyron12233/CodeAssist#53]
Build version: 0.1 ALPHA 
Build date: 1981-01-01 01:01:02 
Current date: 2021-12-14 16:00:15 
Device: Samsung SM-M215F 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.flipkart.android.proteus.value.Value.isBinding()' on a null object reference
	at com.flipkart.android.proteus.processor.AttributeProcessor.process(AttributeProcessor.java:121)
	at com.flipkart.android.proteus.processor.ColorResourceProcessor.evaluate(ColorResourceProcessor.java:47)
	at com.flipkart.android.proteus.value.DrawableValue$RippleValue.apply(DrawableValue.java:602)
	at com.tyron.layoutpreview.inflate.PreviewLayoutInflater.lambda$new$0$PreviewLayoutInflater(PreviewLayoutInflater.java:120)
	at com.tyron.layoutpreview.inflate.PreviewLayoutInflater$$ExternalSyntheticLambda0.getBitmap(Unknown Source:2)
	at com.flipkart.android.proteus.value.DrawableValue$UrlValue.apply(DrawableValue.java:658)
	at com.flipkart.android.proteus.processor.DrawableResourceProcessor.handleValue(DrawableResourceProcessor.java:80)
	at com.flipkart.android.proteus.processor.AttributeProcessor.process(AttributeProcessor.java:130)
	at com.flipkart.android.proteus.ViewTypeParser.handleAttribute(ViewTypeParser.java:192)
	at com.flipkart.android.proteus.ViewTypeParser.handleAttribute(ViewTypeParser.java:174)
	at com.flipkart.android.proteus.SimpleLayoutInflater.handleAttribute(SimpleLayoutInflater.java:208)
	at com.flipkart.android.proteus.SimpleLayoutInflater.inflate(SimpleLayoutInflater.java:109)
	at com.flipkart.android.proteus.parser.custom.ViewGroupParser.handleChildren(ViewGroupParser.java:171)
	at com.flipkart.android.proteus.parser.custom.ViewGroupParser$5.handleValue(ViewGroupParser.java:128)
	at com.flipkart.android.proteus.parser.custom.ViewGroupParser$5.handleValue(ViewGroupParser.java:120)
	at com.flipkart.android.proteus.processor.AttributeProcessor.process(AttributeProcessor.java:130)
	at com.flipkart.android.proteus.ViewTypeParser.handleAttribute(ViewTypeParser.java:192)
	at com.flipkart.android.proteus.ViewTypeParser.handleAttribute(ViewTypeParser.java:174)
	at com.flipkart.android.proteus.SimpleLayoutInflater.handleAttribute(SimpleLayoutInflater.java:208)
	at com.flipkart.android.proteus.SimpleLayoutInflater.inflate(SimpleLayoutInflater.java:109)
	at com.flipkart.android.proteus.parser.custom.ViewGroupParser.handleChildren(ViewGroupParser.java:171)
	at com.flipkart.android.proteus.parser.custom.ViewGroupParser$5.handleValue(ViewGroupParser.java:128)
	at com.flipkart.android.proteus.parser.custom.ViewGroupParser$5.handleValue(ViewGroupParser.java:120)
	at com.flipkart.android.proteus.processor.AttributeProcessor.process(AttributeProcessor.java:130)
	at com.flipkart.android.proteus.ViewTypeParser.handleAttribute(ViewTypeParser.java:192)
	at com.flipkart.android.proteus.ViewTypeParser.handleAttribute(ViewTypeParser.java:174)
	at com.flipkart.android.proteus.SimpleLayoutInflater.handleAttribute(SimpleLayoutInflater.java:208)
	at com.flipkart.android.proteus.SimpleLayoutInflater.inflate(SimpleLayoutInflater.java:109)
	at com.flipkart.android.proteus.SimpleLayoutInflater.inflate(SimpleLayoutInflater.java:145)
	at com.flipkart.android.proteus.SimpleLayoutInflater.inflate(SimpleLayoutInflater.java:157)
	at com.tyron.layoutpreview.inflate.PreviewLayoutInflater.inflateLayout(PreviewLayoutInflater.java:171)
	at com.tyron.code.ui.layoutEditor.LayoutEditorFragment.inflateFile(LayoutEditorFragment.java:229)
	at com.tyron.code.ui.layoutEditor.LayoutEditorFragment.afterParse(LayoutEditorFragment.java:225)
	at com.tyron.code.ui.layoutEditor.LayoutEditorFragment.lambda$createInflater$5$LayoutEditorFragment(LayoutEditorFragment.java:219)
	at com.tyron.code.ui.layoutEditor.LayoutEditorFragment$$ExternalSyntheticLambda4.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8595)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

User actions: 
2021-12-14 15:59:37: MainActivity created
2021-12-14 15:59:37: MainActivity resumed

**Comment by tyron12233** [comment]
Can you send the xml file that you're previewing?

**Comment by rdm600** [comment]
> Can you send the xml file that you're previewing?

![Screenshot_20211214-162118_CodeAssist](https://user-images.githubusercontent.com/53654451/146006243-688f406a-9c4a-4860-9570-3eb2e9d04a25.jpg)
![Screenshot_20211214-162108_CodeAssist](https://user-images.githubusercontent.com/53654451/146006276-a07e71bd-f5c0-4e97-b288-7314993c2f83.jpg)

**Comment by tyron12233** [comment]
Do you have any drawables used in this layout that contains ripple drawable? Can you send it aswell?

**Comment by rdm600** [comment]
> Do you have any drawables used in this layout that contains ripple drawable? Can you send it aswell?

`<?xml version="1.0" encoding="utf-8"?>
<ripple xmlns:android="http://schemas.android.com/apk/res/android"
 android:color="#ffffff">
 <item>
<shape> 
	<solid android:color="#4DC982"/>
     <corners android:radius="7dp"/>
</shape>
 </item>
</ripple>

`

**Comment by tyron12233** [comment]
I have found the issue, thanks!

**Comment by tyron12233** [comment]
Does it still crash on the new version?

**Comment by rdm600** [comment]
> Does it still crash on the new version?

No
