### ISSUE TITLE
Error while opening project from Android Studio

### ISSUE THREAD

**Issue by Kovalit31** [tyron12233/CodeAssist#543]
**Note that Issues are for bugs only. Use the discussions tab for feature requests.**

**Describe the bug**
I copied project (I've got rooted Samsung Edge S7 on PixelExperience with Android 12L and Zarchiver)
I started project and app wanted to crash
**To Reproduce**
Copy Studio project to Android/data/<package>/files/Projects and in app start it

**Expected behavior**
Build version: 0.2.9 ALPHA 
Build date: 1981-01-01 01:01:02 
Current date: 2022-12-29 12:52:39 
Device: Samsung SM-G935F 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
	at com.tyron.xml.completion.repository.api.ResourceNamespace.fromPackageName(ResourceNamespace.java:148)
	at com.tyron.xml.completion.repository.ResourceRepository.<init>(ResourceRepository.java:28)
	at com.tyron.completion.xml.XmlRepository.initialize(XmlRepository.java:90)
	at com.tyron.code.ui.project.ProjectManager.doOpenProject(ProjectManager.java:165)
	at com.tyron.code.ui.project.ProjectManager.lambda$openProject$0$com-tyron-code-ui-project-ProjectManager(ProjectManager.java:94)
	at com.tyron.code.ui.project.ProjectManager$$ExternalSyntheticLambda0.run(Unknown Source:10)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)

User actions: 
2022-12-29 12:52:28: MainActivity created
2022-12-29 12:52:28: MainActivity resumed

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S7 Edge ( hero2lte ) G935F
 - OS: PixelExperience ROM 
 - Version: Android API 32, SQ3A.220705.003
PixelExperience_hero2lte-12.1-20220721-1214-UNOFFICIAL

**Additional context**
no.

**Comment by Kovalit31** [comment]
I found unbaggyed version here, so issue would close.
https://github.com/tyron12233/CodeAssist/suites/8578483717/artifacts/390940625
