### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Reza478** [tyron12233/CodeAssist#544]
Build version: 0.2.9 ALPHA 
Build date: 1981-01-01 01:01:02 
Current date: 2022-12-29 17:38:45 
Device: SHARP SH-04L 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
	at com.tyron.xml.completion.repository.api.ResourceNamespace.fromPackageName(ResourceNamespace.java:148)
	at com.tyron.xml.completion.repository.ResourceRepository.<init>(ResourceRepository.java:28)
	at com.tyron.completion.xml.XmlRepository.initialize(XmlRepository.java:90)
	at com.tyron.code.ui.project.ProjectManager.doOpenProject(ProjectManager.java:165)
	at com.tyron.code.ui.project.ProjectManager.lambda$openProject$0$com-tyron-code-ui-project-ProjectManager(ProjectManager.java:94)
	at com.tyron.code.ui.project.ProjectManager$$ExternalSyntheticLambda0.run(Unknown Source:10)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

User actions: 
2022-12-29 17:33:04: MainActivity created
2022-12-29 17:33:04: MainActivity resumed
2022-12-29 17:33:06: MainActivity paused
2022-12-29 17:33:06: MainActivity destroyed
2022-12-29 17:38:28: MainActivity created
2022-12-29 17:38:28: MainActivity resumed

**Comment by Kovalit31** [comment]
Same error

**Comment by Reza478** [comment]
@Kovalit31 yes I do not know but sometimes it happens

**Comment by Kovalit31** [comment]
@Reza478 I think, it's ms-dos bug. Did you copy your project from Windows? Or you written it's only on device?

**Comment by Kovalit31** [comment]
I found bug code. There is attempt to call equal, when we don't know, is package name not null.
So,![Screenshot_20221230-210629_Acode.png](https://user-images.githubusercontent.com/73341678/210104477-3e76c090-c005-457e-9567-c83246e35d49.png)
It is on 148 line
Maybe assert not working and throws exception, but then it can't be throwable
Or SdkConstants is null...
And in logs hasn't got any exception with jetbrains, so @ NotNull packageName always will be not null. So it can be SdkConstants error. I will find more code for detect reasons.

**Comment by Kovalit31** [comment]
@Reza478 I found apk with fixed crashing. It awailable in codespaces and tyron12233 has already fixed it. So get url. Note: it can be bug with kotlin-android plugin, what i don't recognise. https://github.com/tyron12233/CodeAssist/suites/8578483717/artifacts/390940625
