### ISSUE TITLE
App crash 

### ISSUE THREAD

**Issue by zihadttttttttttt** [tyron12233/CodeAssist#550]
Build version: 0.2.9 ALPHA 
Build date: 1981-01-01 01:01:02 
Current date: 2023-01-09 00:10:20 
Device: Realme RMX2195 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
	at com.tyron.xml.completion.repository.api.ResourceNamespace.fromPackageName(ResourceNamespace.java:148)
	at com.tyron.xml.completion.repository.ResourceRepository.<init>(ResourceRepository.java:28)
	at com.tyron.completion.xml.XmlRepository.initialize(XmlRepository.java:90)
	at com.tyron.code.ui.project.ProjectManager.doOpenProject(ProjectManager.java:165)
	at com.tyron.code.ui.project.ProjectManager.lambda$openProject$0$com-tyron-code-ui-project-ProjectManager(ProjectManager.java:94)
	at com.tyron.code.ui.project.ProjectManager$$ExternalSyntheticLambda0.run(Unknown Source:10)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

User actions: 
2023-01-09 00:10:06: MainActivity created
2023-01-09 00:10:07: MainActivity resumed

**Comment by Kovalit31** [comment]
Use apk from codespaces)

**Comment by Kovalit31** [comment]
No. fork this project and setup actions for Android CI. I think, in internet have lots of information about it
