### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by nandisomnath** [tyron12233/CodeAssist#554]
Build version: 0.2.9 ALPHA 
Build date: 1981-01-01 01:01:02 
Current date: 2023-01-25 17:30:47 
Device: Xiaomi M2101K6P 
 
Stack trace:  
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.get(ArrayList.java:437)
	at com.tyron.code.language.textmate.BaseIncrementalAnalyzeManager$LockedSpans$ReaderImpl.getSpanAt(BaseIncrementalAnalyzeManager.java:428)
	at io.github.rosemoe.sora.widget.EditorPainter.drawRows(EditorPainter.java:860)
	at io.github.rosemoe.sora.widget.EditorPainter.drawView(EditorPainter.java:464)
	at io.github.rosemoe.sora.widget.EditorPainter.draw(EditorPainter.java:128)
	at io.github.rosemoe.sora.widget.CodeEditor.onDraw(CodeEditor.java:3268)
	at com.tyron.code.ui.editor.impl.text.rosemoe.CodeEditorView.onDraw(CodeEditorView.java:456)
	at android.view.View.draw(View.java:23005)
	at android.view.View.updateDisplayListIfDirty(View.java:21873)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4526)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4499)
	at android.view.View.updateDisplayListIfDirty(View.java:21826)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4526)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4499)
	at android.view.View.updateDisplayListIfDirty(View.java:21826)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4526)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4499)
	at android.view.View.updateDisplayListIfDirty(View.java:21826)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4526)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4499)
	at android.view.View.updateDisplayListIfDirty(View.java:21826)
	at android.view.View.draw(View.java:22731)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
	at android.view.View.updateDisplayListIfDirty(View.java:21864)
	at android.view.View.draw(View.java:22731)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1312)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
	at android.view.View.updateDisplayListIfDirty(View.java:21864)
	at android.view.View.draw(View.java:22731)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
	at androidx.fragment.app.FragmentContainerView.drawChild(FragmentContainerView.kt:235)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
	at androidx.fragment.app.FragmentContainerView.dispatchDraw(FragmentContainerView.kt:225)
	at android.view.View.updateDisplayListIfDirty(View.java:21864)
	at android.view.View.draw(View.java:22731)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
	at android.view.View.updateDisplayListIfDirty(View.java:21864)
	at android.view.View.draw(View.java:22731)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
	at android.view.View.updateDisplayListIfDirty(View.java:21864)
	at android.view.View.draw(View.java:22731)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
	at androidx.drawerlayout.widget.DrawerLayout.drawChild(DrawerLayout.java:1478)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
	at android.view.View.updateDisplayListIfDirty(View.java:21864)
	at android.view.View.draw(View.java:22731)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
	at androidx.fragment.app.FragmentContainerView.drawChild(FragmentContainerView.kt:235)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
	at androidx.fragment.app.FragmentContainerView.dispatchDraw(FragmentContainerView.kt:225)
	at android.view.View.updateDisplayListIfDirty(View.java:21864)
	at android.view.View.draw(View.java:22731)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
	at android.view.View.updateDisplayListIfDirty(View.java:21864)
	at android.view.View.draw(View.java:22731)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
	at android.view.View.updateDisplayListIfDirty(View.java:21864)
	at android.view.View.draw(View.java:22731)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
	at android.view.View.updateDisplayListIfDirty(View.java:21864)
	at android.view.View.draw(View.java:22731)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
	at android.view.View.updateDisplayListIfDirty(View.java:21864)
	at android.view.View.draw(View.java:22731)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
	at android.view.View.updateDisplayListIfDirty(View.java:21864)
	at android.view.View.draw(View.java:22731)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
	at android.view.View.draw(View.java:23009)
	at com.android.internal.policy.DecorView.draw(DecorView.java:887)
	at android.view.View.updateDisplayListIfDirty(View.java:21873)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:534)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:542)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:625)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4643)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4361)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3472)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2263)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8984)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1144)
	at android.view.Choreographer.doCallbacks(Choreographer.java:948)
	at android.view.Choreographer.doFrame(Choreographer.java:877)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1129)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8168)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1037)

User actions: 
2023-01-25 17:29:31: MainActivity created
2023-01-25 17:29:31: MainActivity resumed

This report after crash

**Comment by middle1** [comment]
My app is crashing with the same error!

**Comment by middle1** [comment]
My app is crashing with the same error!
