### ISSUE TITLE
Layout Editor Crash

### ISSUE THREAD

**Issue by rdm600** [tyron12233/CodeAssist#57]
Build version: 0.1 ALPHA 
Build date: 1981-01-01 01:01:02 
Current date: 2021-12-15 18:08:01 
Device: Samsung SM-M215F 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Optional com.tyron.layoutpreview.inflate.PreviewLayoutInflater.inflateLayout(java.lang.String)' on a null object reference
	at com.tyron.code.ui.layoutEditor.LayoutEditorFragment.inflateFile(LayoutEditorFragment.java:229)
	at com.tyron.code.ui.layoutEditor.LayoutEditorFragment.afterParse(LayoutEditorFragment.java:225)
	at com.tyron.code.ui.layoutEditor.LayoutEditorFragment.lambda$createInflater$5$LayoutEditorFragment(LayoutEditorFragment.java:219)
	at com.tyron.code.ui.layoutEditor.LayoutEditorFragment$$ExternalSyntheticLambda4.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8595)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

User actions: 
2021-12-15 18:03:46: MainActivity created
2021-12-15 18:03:46: MainActivity resumed

**Comment by rdm600** [comment]
The layout is the same as I sent you, Tyrone

**Comment by tyron12233** [comment]
Is it happening everytime? or just once?

**Comment by rdm600** [comment]
Always

**Comment by tyron12233** [comment]
Fixed in 0.1.7, Reopen the issue if it still persists on the new version.
