### ISSUE TITLE
Crashed on Back Click

### ISSUE THREAD

**Issue by ExtremeKrish** [tyron12233/CodeAssist#58]
```Build version: 0.1.6 ALPHA 
Build date: 1981-01-01 01:01:02 
Current date: 2021-12-16 22:04:40 
Device: Samsung SM-G610F 
 
Stack trace:  
java.lang.IllegalArgumentException: Receiver not registered: com.tyron.code.ui.editor.log.AppLogFragment$1@bc418d6
	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1219)
	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1518)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:664)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:664)
	at com.tyron.code.ui.editor.log.AppLogFragment.onDestroy(AppLogFragment.java:106)
	at androidx.fragment.app.Fragment.performDestroy(Fragment.java:3219)
	at androidx.fragment.app.FragmentStateManager.destroy(FragmentStateManager.java:774)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:350)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
	at androidx.fragment.app.FragmentManager.dispatchDestroy(FragmentManager.java:3107)
	at androidx.fragment.app.Fragment.performDestroy(Fragment.java:3214)
	at androidx.fragment.app.FragmentStateManager.destroy(FragmentStateManager.java:774)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:350)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
	at androidx.fragment.app.FragmentManager.dispatchDestroy(FragmentManager.java:3107)
	at androidx.fragment.app.Fragment.performDestroy(Fragment.java:3214)
	at androidx.fragment.app.FragmentStateManager.destroy(FragmentStateManager.java:774)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:350)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
	at androidx.fragment.app.FragmentManager.dispatchDestroy(FragmentManager.java:3107)
	at androidx.fragment.app.Fragment.performDestroy(Fragment.java:3214)
	at androidx.fragment.app.FragmentStateManager.destroy(FragmentStateManager.java:774)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:350)
	at androidx.fragment.app.SpecialEffectsController$FragmentStateManagerOperation.complete(SpecialEffectsController.java:745)
	at androidx.fragment.app.SpecialEffectsController$Operation.completeSpecialEffect(SpecialEffectsController.java:672)
	at androidx.fragment.app.DefaultSpecialEffectsController$SpecialEffectsInfo.completeSpecialEffect(DefaultSpecialEffectsController.java:776)
	at androidx.fragment.app.DefaultSpecialEffectsController.startAnimations(DefaultSpecialEffectsController.java:147)
	at androidx.fragment.app.DefaultSpecialEffectsController.executeOperations(DefaultSpecialEffectsController.java:120)
	at androidx.fragment.app.SpecialEffectsController.executePendingOperations(SpecialEffectsController.java:297)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2202)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
	at androidx.fragment.app.FragmentManager.popBackStackImmediate(FragmentManager.java:781)
	at androidx.fragment.app.FragmentManager.popBackStackImmediate(FragmentManager.java:692)
	at androidx.fragment.app.FragmentManager.handleOnBackPressed(FragmentManager.java:664)
	at androidx.fragment.app.FragmentManager$1.handleOnBackPressed(FragmentManager.java:436)
	at androidx.activity.OnBackPressedDispatcher.onBackPressed(OnBackPressedDispatcher.java:192)
	at androidx.activity.ComponentActivity.onBackPressed(ComponentActivity.java:543)
	at android.app.Activity.onKeyUp(Activity.java:3114)
	at android.view.KeyEvent.dispatch(KeyEvent.java:3416)
	at androidx.core.view.KeyEventDispatcher.activitySuperDispatchKeyEventPre28(KeyEventDispatcher.java:137)
	at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:87)
	at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:140)
	at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:599)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3090)
	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:486)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5791)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5654)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5151)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5204)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5170)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5307)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5178)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5364)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5151)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5204)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5170)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5178)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5151)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5204)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5170)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5340)
	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:5509)
	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3170)
	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2671)
	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2662)
	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3147)
	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:325)
	at android.os.Looper.loop(Looper.java:142)
	at android.app.ActivityThread.main(ActivityThread.java:7000)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

User actions: 
2021-12-16 21:45:01: MainActivity created
2021-12-16 21:45:01: MainActivity resumed
2021-12-16 21:45:01: MainActivity paused
2021-12-16 21:45:04: MainActivity resumed
2021-12-16 21:46:06: MainActivity paused
2021-12-16 21:46:26: MainActivity resumed
2021-12-16 21:49:48: MainActivity paused
2021-12-16 21:50:20: MainActivity resumed
2021-12-16 21:50:45: MainActivity paused
2021-12-16 21:50:45: SettingsActivity created
2021-12-16 21:50:45: SettingsActivity resumed
2021-12-16 21:50:57: SettingsActivity paused
2021-12-16 21:50:57: MainActivity resumed
2021-12-16 21:50:57: SettingsActivity destroyed
2021-12-16 21:52:47: MainActivity paused
2021-12-16 21:54:50: MainActivity resumed
2021-12-16 21:54:54: MainActivity paused
2021-12-16 21:55:41: MainActivity resumed
2021-12-16 21:55:48: MainActivity paused
2021-12-16 21:55:56: MainActivity resumed
2021-12-16 21:56:34: MainActivity paused
2021-12-16 21:56:41: MainActivity resumed
2021-12-16 21:56:58: MainActivity paused
2021-12-16 21:57:09: MainActivity resumed
2021-12-16 21:57:29: MainActivity paused
2021-12-16 21:57:34: MainActivity resumed
2021-12-16 21:57:38: MainActivity paused
2021-12-16 21:57:43: MainActivity resumed
2021-12-16 21:58:15: MainActivity paused
2021-12-16 21:59:15: MainActivity resumed
2021-12-16 22:00:20: MainActivity paused
2021-12-16 22:00:24: MainActivity resumed
2021-12-16 22:00:39: MainActivity paused
2021-12-16 22:00:42: MainActivity resumed
2021-12-16 22:00:58: MainActivity paused
2021-12-16 22:01:00: MainActivity resumed
2021-12-16 22:01:21: MainActivity paused
2021-12-16 22:01:28: MainActivity resumed
2021-12-16 22:01:46: MainActivity paused
2021-12-16 22:01:47: MainActivity resumed
2021-12-16 22:02:54: MainActivity paused
2021-12-16 22:03:05: MainActivity resumed
2021-12-16 22:03:28: MainActivity paused
2021-12-16 22:03:37: MainActivity resumed
2021-12-16 22:04:04: MainActivity paused
2021-12-16 22:04:12: MainActivity resumed
```

**Comment by tyron12233** [comment]
fixed, thanks.
