### ISSUE TITLE
Error while switching between this and another app

### ISSUE THREAD

**Issue by sky64redstone** [tyron12233/CodeAssist#583]
**Describe the bug**
I just got a error page on the screen with 2 buttons: restart app & show stacktrance

**To Reproduce**
I couldn't reproduce the error but I think it was when I switched between this and another app

**Expected behavior**
I just opened the app from the background again, and there came the error 

**Smartphone (please complete the following information):**
 - Android Version 6
Build version: 0.2.9 ALPHA 
Build date: 1981-01-01 01:01:02 
Current date: 2023-05-30 19:15:19 
Device: HUAWEI FIG-LX1  

**Additional context**
Here is the error:
 
Stack trace:  
java.lang.IndexOutOfBoundsException: Index: 10, Size: 1
	at java.util.ArrayList.get(ArrayList.java:437)
	at com.tyron.code.language.textmate.BaseIncrementalAnalyzeManager$LockedSpans$ReaderImpl.getSpanAt(BaseIncrementalAnalyzeManager.java:428)
	at io.github.rosemoe.sora.widget.EditorPainter.drawRows(EditorPainter.java:839)
	at io.github.rosemoe.sora.widget.EditorPainter.drawView(EditorPainter.java:464)
	at io.github.rosemoe.sora.widget.EditorPainter.draw(EditorPainter.java:128)
	at io.github.rosemoe.sora.widget.CodeEditor.onDraw(CodeEditor.java:3268)
	at com.tyron.code.ui.editor.impl.text.rosemoe.CodeEditorView.onDraw(CodeEditorView.java:456)
	at android.view.View.draw(View.java:20483)
	at android.view.View.updateDisplayListIfDirty(View.java:19294)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4375)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4348)
	at android.view.View.updateDisplayListIfDirty(View.java:19254)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4375)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4348)
	at android.view.View.updateDisplayListIfDirty(View.java:19254)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4375)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4348)
	at android.view.View.updateDisplayListIfDirty(View.java:19254)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4375)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4348)
	at android.view.View.updateDisplayListIfDirty(View.java:19254)
	at android.view.View.draw(View.java:20211)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4394)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4170)
	at android.view.View.updateDisplayListIfDirty(View.java:19285)
	at android.view.View.draw(View.java:20211)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4394)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1312)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4170)
	at android.view.View.updateDisplayListIfDirty(View.java:19285)
	at android.view.View.draw(View.java:20211)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4394)
	at androidx.fragment.app.FragmentContainerView.drawChild(FragmentContainerView.kt:235)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4170)
	at androidx.fragment.app.FragmentContainerView.dispatchDraw(FragmentContainerView.kt:225)
	at android.view.View.updateDisplayListIfDirty(View.java:19285)
	at android.view.View.draw(View.java:20211)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4394)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4170)
	at android.view.View.updateDisplayListIfDirty(View.java:19285)
	at android.view.View.draw(View.java:20211)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4394)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4170)
	at android.view.View.updateDisplayListIfDirty(View.java:19285)
	at android.view.View.draw(View.java:20211)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4394)
	at androidx.drawerlayout.widget.DrawerLayout.drawChild(DrawerLayout.java:1478)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4170)
	at android.view.View.updateDisplayListIfDirty(View.java:19285)
	at android.view.View.draw(View.java:20211)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4394)
	at androidx.fragment.app.FragmentContainerView.drawChild(FragmentContainerView.kt:235)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4170)
	at androidx.fragment.app.FragmentContainerView.dispatchDraw(FragmentContainerView.kt:225)
	at android.view.View.updateDisplayListIfDirty(View.java:19285)
	at android.view.View.draw(View.java:20211)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4394)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4170)
	at android.view.View.updateDisplayListIfDirty(View.java:19285)
	at android.view.View.draw(View.java:20211)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4394)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4170)
	at android.view.View.updateDisplayListIfDirty(View.java:19285)
	at android.view.View.draw(View.java:20211)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4394)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4170)
	at android.view.View.updateDisplayListIfDirty(View.java:19285)
	at android.view.View.draw(View.java:20211)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4394)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4170)
	at android.view.View.updateDisplayListIfDirty(View.java:19285)
	at android.view.View.draw(View.java:20211)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4394)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4170)
	at android.view.View.updateDisplayListIfDirty(View.java:19285)
	at android.view.View.draw(View.java:20211)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4394)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4170)
	at android.view.View.draw(View.java:20486)
	at com.android.internal.policy.DecorView.draw(DecorView.java:928)
	at android.view.View.updateDisplayListIfDirty(View.java:19294)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:740)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:746)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:861)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3583)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3379)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2711)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1633)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7943)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092)
	at android.view.Choreographer.doCallbacks(Choreographer.java:893)
	at android.view.Choreographer.doFrame(Choreographer.java:812)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
	at android.os.Handler.handleCallback(Handler.java:907)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

User actions: 
2023-05-30 19:00:55: MainActivity created
2023-05-30 19:00:55: MainActivity resumed
2023-05-30 19:02:18: MainActivity paused
2023-05-30 19:05:16: MainActivity resumed
2023-05-30 19:05:53: MainActivity paused
2023-05-30 19:05:55: MainActivity resumed
2023-05-30 19:06:06: MainActivity paused
2023-05-30 19:06:09: MainActivity resumed
2023-05-30 19:06:23: MainActivity paused
2023-05-30 19:06:25: MainActivity resumed
2023-05-30 19:06:30: MainActivity paused
2023-05-30 19:06:31: MainActivity resumed
2023-05-30 19:06:32: MainActivity paused
2023-05-30 19:06:34: MainActivity resumed
2023-05-30 19:06:51: MainActivity paused
2023-05-30 19:06:55: MainActivity resumed
2023-05-30 19:06:57: MainActivity paused
2023-05-30 19:06:58: MainActivity resumed
2023-05-30 19:07:14: MainActivity paused
2023-05-30 19:07:19: MainActivity resumed
2023-05-30 19:07:28: MainActivity paused
2023-05-30 19:07:31: MainActivity resumed
2023-05-30 19:07:59: MainActivity paused
2023-05-30 19:08:01: MainActivity resumed
2023-05-30 19:08:03: MainActivity paused
2023-05-30 19:08:04: MainActivity resumed
2023-05-30 19:08:14: MainActivity paused
2023-05-30 19:08:33: MainActivity resumed
2023-05-30 19:08:57: MainActivity paused
2023-05-30 19:09:00: MainActivity resumed
2023-05-30 19:09:08: MainActivity paused
2023-05-30 19:09:10: MainActivity resumed
2023-05-30 19:09:19: MainActivity paused
2023-05-30 19:09:23: MainActivity resumed
2023-05-30 19:10:03: MainActivity paused
2023-05-30 19:10:11: MainActivity resumed
2023-05-30 19:10:24: MainActivity paused
2023-05-30 19:10:25: MainActivity resumed
2023-05-30 19:10:28: MainActivity paused
2023-05-30 19:10:32: MainActivity resumed
2023-05-30 19:10:36: MainActivity paused
2023-05-30 19:10:38: MainActivity resumed
2023-05-30 19:10:42: MainActivity paused
2023-05-30 19:10:47: MainActivity resumed
2023-05-30 19:10:52: MainActivity paused
2023-05-30 19:11:01: MainActivity resumed
2023-05-30 19:11:42: MainActivity paused
2023-05-30 19:11:54: MainActivity resumed
2023-05-30 19:12:01: MainActivity paused
2023-05-30 19:12:21: MainActivity resumed
2023-05-30 19:13:21: MainActivity paused
2023-05-30 19:13:29: MainActivity resumed
2023-05-30 19:13:46: MainActivity paused
2023-05-30 19:13:49: MainActivity resumed
2023-05-30 19:14:10: MainActivity paused
2023-05-30 19:14:16: MainActivity resumed
2023-05-30 19:14:29: MainActivity paused
2023-05-30 19:14:31: MainActivity resumed
2023-05-30 19:14:43: MainActivity paused
2023-05-30 19:14:47: MainActivity resumed
2023-05-30 19:14:56: MainActivity paused
2023-05-30 19:14:59: MainActivity resumed
- -

**Comment by Shimulcd** [comment]
Facebook clone code
