### ISSUE TITLE
App crashes when using code completion

### ISSUE THREAD

**Issue by Professionalprogrammers123** [tyron12233/CodeAssist#586]
Build version: 0.2.9 ALPHA 
Build date: 1981-01-01 01:01:02 
Current date: 2023-06-07 07:09:11 
Device: TECNO MOBILE LIMITED TECNO BD2 
 
Stack trace:  
java.lang.IndexOutOfBoundsException: Index: 11, Size: 1
	at java.util.ArrayList.get(ArrayList.java:437)
	at com.tyron.code.language.textmate.BaseIncrementalAnalyzeManager$LockedSpans$ReaderImpl.getSpanAt(BaseIncrementalAnalyzeManager.java:428)
	at io.github.rosemoe.sora.widget.EditorPainter.drawRows(EditorPainter.java:860)
	at io.github.rosemoe.sora.widget.EditorPainter.drawView(EditorPainter.java:464)
	at io.github.rosemoe.sora.widget.EditorPainter.draw(EditorPainter.java:128)
	at io.github.rosemoe.sora.widget.CodeEditor.onDraw(CodeEditor.java:3268)
	at com.tyron.code.ui.editor.impl.text.rosemoe.CodeEditorView.onDraw(CodeEditorView.java:456)
	at android.view.View.draw(View.java:21494)
	at android.view.View.updateDisplayListIfDirty(View.java:20371)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4390)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4363)
	at android.view.View.updateDisplayListIfDirty(View.java:20331)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4390)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4363)
	at android.view.View.updateDisplayListIfDirty(View.java:20331)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4390)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4363)
	at android.view.View.updateDisplayListIfDirty(View.java:20331)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4390)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4363)
	at android.view.View.updateDisplayListIfDirty(View.java:20331)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4390)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4363)
	at android.view.View.updateDisplayListIfDirty(View.java:20331)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4390)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4363)
	at android.view.View.updateDisplayListIfDirty(View.java:20331)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4390)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4363)
	at android.view.View.updateDisplayListIfDirty(View.java:20331)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4390)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4363)
	at android.view.View.updateDisplayListIfDirty(View.java:20331)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4390)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4363)
	at android.view.View.updateDisplayListIfDirty(View.java:20331)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4390)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4363)
	at android.view.View.updateDisplayListIfDirty(View.java:20331)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4390)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4363)
	at android.view.View.updateDisplayListIfDirty(View.java:20331)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4390)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4363)
	at android.view.View.updateDisplayListIfDirty(View.java:20331)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4390)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4363)
	at android.view.View.updateDisplayListIfDirty(View.java:20331)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4390)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4363)
	at android.view.View.updateDisplayListIfDirty(View.java:20331)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4390)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4363)
	at android.view.View.updateDisplayListIfDirty(View.java:20331)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4390)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4363)
	at android.view.View.updateDisplayListIfDirty(View.java:20331)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4390)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4363)
	at android.view.View.updateDisplayListIfDirty(View.java:20331)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:575)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:581)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:654)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3657)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3465)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2794)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1760)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7646)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
	at android.view.Choreographer.doCallbacks(Choreographer.java:790)
	at android.view.Choreographer.doFrame(Choreographer.java:725)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7649)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:503)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

User actions: 
2023-06-07 07:07:44: MainActivity created
2023-06-07 07:07:44: MainActivity resumed

**Comment by ElktrumElk** [comment]
I have created a simple riddle game but when I launch the app and press the play button it crashes saying that Riddle has stopped and the code is complete no error while compiling but it crashes

**Comment by Professionalprogrammers123** [comment]
There is a line in your code that causes the app to crash
