### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by bharatkumarchoudhary77** [tyron12233/CodeAssist#621]
**Note that Issues are for bugs only. Use the discussions tab for feature requests.**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

![Screenshot_2023-10-01-13-20-57-48_2870cb4d7e72f8050b62d08052357b72.jpg](https://github.com/tyron12233/CodeAssist/assets/146069609/268c6572-8dbe-4e37-99ee-2860c923d3f4)

![Screenshot_2023-10-01-13-19-50-54_2870cb4d7e72f8050b62d08052357b72.jpg](https://github.com/tyron12233/CodeAssist/assets/146069609/65443273-e7c3-48e1-a4d9-7e1f2a747112)

**Comment by bharatkumarchoudhary77** [comment]
Build version: 0.2.9 ALPHA 
Build date: 1981-01-01 01:01:02 
Current date: 2023-10-03 14:57:52 
Device: Realme RMX1931 
 
Stack trace:  
java.lang.IndexOutOfBoundsException: Index: 3, Size: 1
	at java.util.ArrayList.get(ArrayList.java:437)
	at com.tyron.code.language.textmate.BaseIncrementalAnalyzeManager$LockedSpans$ReaderImpl.getSpanAt(BaseIncrementalAnalyzeManager.java:428)
	at io.github.rosemoe.sora.widget.EditorPainter.updateLineDisplayList(EditorPainter.java:395)
	at io.github.rosemoe.sora.widget.HwAcceleratedRenderer.drawLineHardwareAccelerated(HwAcceleratedRenderer.java:127)
	at io.github.rosemoe.sora.widget.EditorPainter.drawRows(EditorPainter.java:1014)
	at io.github.rosemoe.sora.widget.EditorPainter.drawView(EditorPainter.java:464)
	at io.github.rosemoe.sora.widget.EditorPainter.draw(EditorPainter.java:128)
	at io.github.rosemoe.sora.widget.CodeEditor.onDraw(CodeEditor.java:3268)
	at com.tyron.code.ui.editor.impl.text.rosemoe.CodeEditorView.onDraw(CodeEditorView.java:456)
	at android.view.View.draw(View.java:22639)
	at android.view.View.updateDisplayListIfDirty(View.java:21492)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4569)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4542)
	at android.view.View.updateDisplayListIfDirty(View.java:21452)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4569)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4542)
	at android.view.View.updateDisplayListIfDirty(View.java:21452)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4569)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4542)
	at android.view.View.updateDisplayListIfDirty(View.java:21452)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4569)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4542)
	at android.view.View.updateDisplayListIfDirty(View.java:21452)
	at android.view.View.draw(View.java:22359)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4589)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4323)
	at android.view.View.updateDisplayListIfDirty(View.java:21483)
	at android.view.View.draw(View.java:22359)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4589)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1312)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4323)
	at android.view.View.updateDisplayListIfDirty(View.java:21483)
	at android.view.View.draw(View.java:22359)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4589)
	at androidx.fragment.app.FragmentContainerView.drawChild(FragmentContainerView.kt:235)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4323)
	at androidx.fragment.app.FragmentContainerView.dispatchDraw(FragmentContainerView.kt:225)
	at android.view.View.updateDisplayListIfDirty(View.java:21483)
	at android.view.View.draw(View.java:22359)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4589)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4323)
	at android.view.View.updateDisplayListIfDirty(View.java:21483)
	at android.view.View.draw(View.java:22359)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4589)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4323)
	at android.view.View.updateDisplayListIfDirty(View.java:21483)
	at android.view.View.draw(View.java:22359)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4589)
	at androidx.drawerlayout.widget.DrawerLayout.drawChild(DrawerLayout.java:1478)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4323)
	at android.view.View.updateDisplayListIfDirty(View.java:21483)
	at android.view.View.draw(View.java:22359)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4589)
	at androidx.fragment.app.FragmentContainerView.drawChild(FragmentContainerView.kt:235)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4323)
	at androidx.fragment.app.FragmentContainerView.dispatchDraw(FragmentContainerView.kt:225)
	at android.view.View.updateDisplayListIfDirty(View.java:21483)
	at android.view.View.draw(View.java:22359)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4589)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4323)
	at android.view.View.updateDisplayListIfDirty(View.java:21483)
	at android.view.View.draw(View.java:22359)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4589)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4323)
	at android.view.View.updateDisplayListIfDirty(View.java:21483)
	at android.view.View.draw(View.java:22359)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4589)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4323)
	at android.view.View.updateDisplayListIfDirty(View.java:21483)
	at android.view.View.draw(View.java:22359)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4589)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4323)
	at android.view.View.updateDisplayListIfDirty(View.java:21483)
	at android.view.View.draw(View.java:22359)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4589)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4323)
	at android.view.View.updateDisplayListIfDirty(View.java:21483)
	at android.view.View.draw(View.java:22359)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4589)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4323)
	at com.android.internal.policy.DecorView.dispatchDraw(DecorView.java:2954)
	at android.view.View.draw(View.java:22642)
	at com.android.internal.policy.DecorView.draw(DecorView.java:895)
	at android.view.View.updateDisplayListIfDirty(View.java:21492)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:565)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:642)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4510)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4225)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3456)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2252)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8791)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1137)
	at android.view.Choreographer.doCallbacks(Choreographer.java:959)
	at android.view.Choreographer.doFrame(Choreographer.java:884)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1122)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:254)
	at android.app.ActivityThread.main(ActivityThread.java:8219)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)

User actions: 
2023-10-03 14:39:06: MainActivity created
2023-10-03 14:39:06: MainActivity resumed
2023-10-03 14:39:09: MainActivity paused
2023-10-03 14:39:17: MainActivity resumed
2023-10-03 14:39:22: MainActivity paused
2023-10-03 14:41:51: MainActivity resumed
2023-10-03 14:47:25: MainActivity paused
2023-10-03 14:47:26: MainActivity resumed
2023-10-03 14:47:28: MainActivity paused
2023-10-03 14:48:06: MainActivity resumed
2023-10-03 14:48:30: MainActivity paused
2023-10-03 14:48:35: MainActivity resumed
2023-10-03 14:48:49: MainActivity paused
2023-10-03 14:48:54: MainActivity resumed
2023-10-03 14:49:00: MainActivity paused
2023-10-03 14:49:35: MainActivity resumed
2023-10-03 14:50:08: MainActivity paused
2023-10-03 14:50:22: MainActivity resumed
2023-10-03 14:50:24: MainActivity paused
2023-10-03 14:50:41: MainActivity resumed
2023-10-03 14:50:43: MainActivity paused
2023-10-03 14:50:46: MainActivity resumed
2023-10-03 14:51:09: MainActivity paused
2023-10-03 14:51:21: MainActivity resumed
2023-10-03 14:51:33: MainActivity paused
2023-10-03 14:51:37: MainActivity resumed
2023-10-03 14:51:48: MainActivity paused
2023-10-03 14:51:51: MainActivity resumed
2023-10-03 14:51:59: MainActivity paused
2023-10-03 14:52:00: MainActivity resumed
2023-10-03 14:52:08: MainActivity paused
2023-10-03 14:52:19: MainActivity resumed
2023-10-03 14:52:41: MainActivity paused
2023-10-03 14:52:50: MainActivity resumed
2023-10-03 14:53:00: MainActivity paused
2023-10-03 14:53:14: MainActivity resumed
2023-10-03 14:54:21: MainActivity paused
2023-10-03 14:54:31: MainActivity resumed
2023-10-03 14:54:43: MainActivity paused
2023-10-03 14:54:45: MainActivity resumed
2023-10-03 14:54:50: MainActivity paused
2023-10-03 14:54:53: MainActivity resumed
2023-10-03 14:55:03: MainActivity paused
2023-10-03 14:55:06: MainActivity resumed
2023-10-03 14:55:14: MainActivity paused
2023-10-03 14:55:18: MainActivity resumed
2023-10-03 14:55:30: MainActivity paused
2023-10-03 14:55:35: MainActivity resumed
2023-10-03 14:55:47: MainActivity paused
2023-10-03 14:55:56: MainActivity resumed
2023-10-03 14:56:04: MainActivity paused
2023-10-03 14:56:24: MainActivity resumed
2023-10-03 14:57:06: MainActivity paused
2023-10-03 14:57:16: MainActivity resumed
