### ISSUE TITLE
The app that was compiled with code assist is broken

### ISSUE THREAD

**Issue by GEOEGII555** [tyron12233/CodeAssist#653]
**Describe the bug**

I created a new blank Jetpack Compose project and clicked the build release button after it downloaded the libraries (no code modifications), the app that was built by code assist (not code assist itself, the app that was built from it) is broken.

**To Reproduce**
1. Create a new jetpack compose project
You can call the app anything, I called it "Telegram Spam" (why not?)
2. Click on 'Build APK-release'
3. Run the app that just got built

**Expected behavior**
The app should launch normally, and show "Hello world!" if you just created it (like described in this bug report)

**Screenshots**
![Screenshot_2024-02-02-23-09-54-692_com.miui.bugreport-edit.jpg](https://github.com/tyron12233/CodeAssist/assets/57674559/ca1a88a8-4bbf-4191-89dc-f68033e8e9cd)
<details><summary>The error, but as text</summary>
<pre>
java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{geoegii555.telegramspam/geoegii555.telegramspam.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "geoegii555.telegramspam.MainActivity" on path: DexPathList[[zip file "/data/app/~~9Nejc7k5qMjGuhZ-h0BRlA==/geoegii555.telegramspam-aC_Lz9v0IQhylOZopocIvQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~9Nejc7k5qMjGuhZ-h0BRlA==/geoegii555.telegramspam-aC_Lz9v0IQhylOZopocIvQ==/lib/arm64, /system/lib64, /system_ext/lib64]]
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3775)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4018)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2427)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8232)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
Caused by: java.lang.ClassNotFoundException: Didn't find class "geoegii555.telegramspam.MainActivity" on path: DexPathList[[zip file "/data/app/~~9Nejc7k5qMjGuhZ-h0BRlA==/geoegii555.telegramspam-aC_Lz9v0IQhylOZopocIvQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~9Nejc7k5qMjGuhZ-h0BRlA==/geoegii555.telegramspam-aC_Lz9v0IQhylOZopocIvQ==/lib/arm64, /system/lib64, /system_ext/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
	at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
	at android.app.Instrumentation.newActivity(Instrumentation.java:1359)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3762)
	... 12 more
</pre>
</details>

**Smartphone (please complete the following information):**
 - Device: Redmi Note 10S
 - OS: MIUI
 - Version 14.0.8

**Additional context**

I will repeat it again - no code modifications were made, I just created a jetpack compose project and built it.

*edit: fixing the spelling mistakes*

**Comment by GEOEGII555** [comment]
_stale_
