### ISSUE TITLE
Editor crash

### ISSUE THREAD

**Issue by rdm600** [tyron12233/CodeAssist#66]
Build version: 0.1.6 ALPHA 
Build date: 1981-01-01 01:01:02 
Current date: 2021-12-17 20:24:50 
Device: Samsung SM-M215F 
 
Stack trace:  
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.get(ArrayList.java:437)
	at com.tyron.code.ui.editor.CompletionItemAdapter.getItem(CompletionItemAdapter.java:110)
	at io.github.rosemoe.sora.widget.EditorAutoCompleteWindow.select(EditorAutoCompleteWindow.java:217)
	at io.github.rosemoe.sora.widget.EditorAutoCompleteWindow.select(EditorAutoCompleteWindow.java:205)
	at io.github.rosemoe.sora.widget.CodeEditor.onKeyDown(CodeEditor.java:4729)
	at android.view.KeyEvent.dispatch(KeyEvent.java:3624)
	at android.view.View.dispatchKeyEvent(View.java:15050)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1986)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1986)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1986)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1986)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1986)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1986)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1986)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1986)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1986)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1986)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1986)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1986)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1986)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1986)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1986)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1986)
	at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:903)
	at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1947)
	at android.app.Activity.dispatchKeyEvent(Activity.java:4142)
	at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:122)
	at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:84)
	at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:140)
	at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:599)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3090)
	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:758)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:7365)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7191)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6595)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6652)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6618)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6786)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6626)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6843)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6599)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6652)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6618)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6626)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6599)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9880)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9718)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9671)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:6206)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8595)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

User actions: 
2021-12-17 19:40:36: MainActivity created
2021-12-17 19:40:36: MainActivity resumed
2021-12-17 19:42:04: MainActivity paused
2021-12-17 19:42:42: MainActivity resumed
2021-12-17 19:47:15: MainActivity paused
2021-12-17 19:47:23: MainActivity resumed
2021-12-17 19:48:46: MainActivity paused
2021-12-17 19:51:17: MainActivity resumed
2021-12-17 19:53:27: MainActivity paused
2021-12-17 19:55:42: MainActivity resumed
2021-12-17 19:57:11: MainActivity paused
2021-12-17 19:58:58: MainActivity resumed
2021-12-17 19:59:15: MainActivity paused
2021-12-17 19:59:17: MainActivity resumed
2021-12-17 20:05:21: MainActivity paused
2021-12-17 20:05:27: MainActivity resumed
2021-12-17 20:09:54: MainActivity paused
2021-12-17 20:10:45: MainActivity resumed
2021-12-17 20:16:54: MainActivity paused
2021-12-17 20:17:05: MainActivity resumed
2021-12-17 20:17:05: MainActivity paused
2021-12-17 20:17:06: MainActivity resumed
2021-12-17 20:17:33: MainActivity paused
2021-12-17 20:17:55: MainActivity resumed
2021-12-17 20:20:29: MainActivity paused
2021-12-17 20:21:09: MainActivity resumed
2021-12-17 20:21:51: MainActivity paused
2021-12-17 20:21:58: MainActivity resumed
2021-12-17 20:22:39: MainActivity paused
2021-12-17 20:22:53: MainActivity resumed
2021-12-17 20:22:57: MainActivity paused
2021-12-17 20:23:07: MainActivity resumed

**Comment by tyron12233** [comment]
is it with kotlin completions enabled?

**Comment by rdm600** [comment]
> is it with kotlin completions enabled?

No, Java. It happened when I wrote @Override and made a transfer

**Comment by tyron12233** [comment]
Fixed in 0.1.7, Reopen the issue if it still persists on the new version.
