### ISSUE TITLE
Broke

### ISSUE THREAD

**Issue by HyperionElectronicsCo** [tyron12233/CodeAssist#663]
Build version: 0.2.9 ALPHA 
Build date: 1981-01-01 01:01:02 
Current date: 2024-02-28 23:35:21 
Device: HUAWEI EVR-N29 
 
Stack trace:  
java.lang.OutOfMemoryError: Failed to allocate a 420546432 byte allocation with 25165824 free bytes and 231MB until OOM, target footprint 319806760, growth limit 536870912
	at java.util.Arrays.copyOf(Arrays.java:3136)
	at java.util.Arrays.copyOf(Arrays.java:3106)
	at java.util.ArrayList.grow(ArrayList.java:275)
	at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:249)
	at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:241)
	at java.util.ArrayList.add(ArrayList.java:467)
	at com.tyron.completion.xml.BytecodeScanner.getSuperClasses(BytecodeScanner.java:163)
	at com.tyron.completion.xml.BytecodeScanner.isViewClass(BytecodeScanner.java:140)
	at com.tyron.completion.xml.BytecodeScanner.lambda$scan$2(BytecodeScanner.java:81)
	at com.tyron.completion.xml.BytecodeScanner$$ExternalSyntheticLambda2.accept(Unknown Source:4)
	at com.tyron.completion.xml.BytecodeScanner.iterate(BytecodeScanner.java:199)
	at com.tyron.completion.xml.BytecodeScanner.iterateClasses(BytecodeScanner.java:189)
	at com.tyron.completion.xml.BytecodeScanner.scan(BytecodeScanner.java:76)
	at com.tyron.completion.xml.XmlRepository.initialize(XmlRepository.java:111)
	at com.tyron.code.ui.project.ProjectManager.doOpenProject(ProjectManager.java:165)
	at com.tyron.code.ui.project.ProjectManager.lambda$openProject$0$com-tyron-code-ui-project-ProjectManager(ProjectManager.java:94)
	at com.tyron.code.ui.project.ProjectManager$$ExternalSyntheticLambda0.run(Unknown Source:10)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)

User actions: 
2024-02-28 23:32:31: MainActivity created
2024-02-28 23:32:31: MainActivity resumed
2024-02-28 23:32:33: MainActivity paused
2024-02-28 23:33:10: MainActivity resumed
2024-02-28 23:33:14: MainActivity paused
2024-02-28 23:33:15: MainActivity destroyed
2024-02-28 23:34:11: MainActivity created
2024-02-28 23:34:11: MainActivity resumed

**Comment by HyperionElectronicsCo** [comment]
2 years later 🫢

package com.tyron.completion.xml;

import android.content.Context;
import android.util.AttributeSet;
import android.view.View;
import android.view.ViewGroup;

import com.google.common.collect.ImmutableSet;
import com.tyron.builder.BuildModule;
import com.tyron.completion.xml.util.PartialClassParser;

import org.apache.bcel.Repository;
import org.apache.bcel.classfile.JavaClass;
import org.apache.bcel.classfile.Method;
import org.apache.bcel.generic.Type;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.Enumeration;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;
import java.util.function.Consumer;
import java.util.function.Predicate;
import java.util.jar.JarEntry;
import java.util.jar.JarFile;

/**
 * Scans jar files and saves all the class files that extends {@link View} and has the
 * appropriate constructors to be inflated in XML.
 */
public class BytecodeScanner {

    private static final Predicate<String> CLASS_NAME_FILTER = s -> s.endsWith(".class");

    private static final Set<String> sIgnoredPaths;
    
    // Caches to avoid redundant deep hierarchy scans for recurring parent classes
    private static final Map<String, Boolean> sViewClassCache = new ConcurrentHashMap<>();
    private static final Map<String, Boolean> sViewGroupCache = new ConcurrentHashMap<>();

    static {
        ImmutableSet.Builder<String> builder = ImmutableSet.builder();
        builder.add("android");
        builder.add("android/util");
        builder.add("android/os");
        builder.add("android/os/health");
        builder.add("android/os/strictmode");
        builder.add("android/os/storage");
        builder.add("android/graphics");
        builder.add("android/graphics/drawable");
        builder.add("android/graphics/fonts");
        builder.add("android/graphics/pdf");
        builder.add("android/graphics/text");
        builder.add("android/system");
        builder.add("android/content");
        builder.add("android/content/res");
        builder.add("android/content/pm");
        sIgnoredPaths = builder.build();
    }

    public static void loadJar(File jar) throws IOException {
        try (JarFile jarFile = new JarFile(jar)) {
            iterateClasses(jarFile, element -> {
                PartialClassParser classParser =
                        new PartialClassParser(jar.getAbsolutePath(), element.getName());
                try {
                    Repository.addClass(classParser.parse());
                } catch (IOException e) {
                    // ignored, keep parsing other classes
                }
            });
        }
    }

    public static List<JavaClass> scan(File file) throws IOException {
        List<JavaClass> viewClasses = new ArrayList<>();
        try (JarFile jarFile = new JarFile(file)) {
            iterateClasses(jarFile, element -> {
                String fqn = element.getName().replace('/', '.')
                        .substring(0, element.getName().length() - ".class".length());
                try {
                    JavaClass javaClass = Repository.lookupClass(fqn);
                    if (isViewClass(javaClass)) {
                        viewClasses.add(javaClass);
                    }
                } catch (ClassNotFoundException e) {
                    // should not happen, the class should already be loaded here.
                }
            });
        }
        return viewClasses;
    }

    public static boolean isViewGroup(JavaClass javaClass) {
        if (javaClass == null) {
            return false;
        }
        String className = javaClass.getClassName();
        if (sViewGroupCache.containsKey(className)) {
            return sViewGroupCache.get(className);
        }

        JavaClass[] superClasses = getSuperClasses(javaClass);
        boolean result = Arrays.stream(superClasses)
                .anyMatch(it -> ViewGroup.class.getName().equals(it.getClassName()));
        
        sViewGroupCache.put(className, result);
        return result;
    }

    public static void scanBootstrapIfNeeded() {
        if (!needScanBootstrap()) {
            return;
        }

        File androidJar = BuildModule.getAndroidJar();
        if (androidJar != null && androidJar.exists()) {
            try (JarFile jarFile = new JarFile(androidJar)) {
                iterateClasses(jarFile, element -> {
                    String name = element.getName();
                    String packagePath = name.substring(0, name.lastIndexOf('/'));
                    if (sIgnoredPaths.contains(packagePath)) {
                        return;
                    }
                    if (packagePath.startsWith("java/")) {
                        return;
                    }
                    PartialClassParser classParser =
                            new PartialClassParser(androidJar.getAbsolutePath(), name);
                    try {
                        Repository.addClass(classParser.parse());
                    } catch (IOException e) {
                        // ignored, keep parsing other classes
                    }

                });
            } catch (IOException e) {
                // ignored
            }
        }
    }

    private static boolean needScanBootstrap() {
        try {
            Repository.getRepository().loadClass(View.class);
            return false;
        } catch (ClassNotFoundException e) {
            return true;
        }
    }

    private static boolean isViewClass(JavaClass javaClass) {
        if (javaClass == null) {
            return false;
        }
        String className = javaClass.getClassName();
        if (sViewClassCache.containsKey(className)) {
            return sViewClassCache.get(className);
        }

        JavaClass[] superClasses = getSuperClasses(javaClass);
        boolean result = Arrays.stream(superClasses)
                .anyMatch(it -> View.class.getName().equals(it.getClassName()));
        
        sViewClassCache.put(className, result);
        return result;
    }

    /**
     * Get the array of java classes even if the root class does not exist.
     * Prevents infinite loops caused by circular dependencies or self-referential bytecode.
     *
     * @param javaClass The java class
     * @return array of super classes
     */
    public static JavaClass[] getSuperClasses(JavaClass javaClass) {
        if (javaClass == null) {
            return new JavaClass[0];
        }

        List<JavaClass> superClasses = new ArrayList<>();
        Set<String> visitedClassNames = new HashSet<>();
        
        JavaClass current = javaClass;
        visitedClassNames.add(current.getClassName());

        while (current != null && current.getSuperclassName() != null) {
            String superClassName = current.getSuperclassName();

            // Guard against infinite circular inheritance trees or self-referencing definitions
            if (visitedClassNames.contains(superClassName)) {
                break; 
            }
            visitedClassNames.add(superClassName);

            JavaClass lookupClass;
            try {
                lookupClass = Repository.lookupClass(superClassName);
            } catch (ClassNotFoundException e) {
                lookupClass = null;
            }

            if (lookupClass != null) {
                superClasses.add(lookupClass);
            }
            current = lookupClass;
        }
        return superClasses.toArray(new JavaClass[0]);
    }

    private static boolean containsViewConstructors(Method[] methods) {
        for (Method method : methods) {
            if (!"<init>".equals(method.getName())) {
                continue;
            }

            Type[] argumentTypes = method.getArgumentTypes();
            if (argumentTypes.length == 2) {
                if (Context.class.getName().equals(argumentTypes[0].toString())) {
                    if (AttributeSet.class.getName().equals(argumentTypes[1].toString())) {
                        return true;
                    }
                }
            }
        }
        return false;
    }

    public static void iterateClasses(JarFile jarFile, Consumer<JarEntry> consumer) {
        iterate(jarFile, CLASS_NAME_FILTER, consumer);
    }

    public static void iterate(JarFile jarFile,
                               Predicate<String> nameFilter,
                               Consumer<JarEntry> consumer) {
        Enumeration<JarEntry> entries = jarFile.entries();
        while (entries.hasMoreElements()) {
            JarEntry entry = entries.nextElement();
            if (nameFilter.test(entry.getName())) {
                consumer.accept(entry);
            }
        }
    }
}
