### ISSUE TITLE
I cannot even delete a word without crashing

### ISSUE THREAD

**Issue by LordYoElGrande** [tyron12233/CodeAssist#707]
I was programming my app with kotlin. Everything worked. But know, each time I try to delete part of my code, the app (Code Assists) crashes and shows me this error:

`Build version: 0.2.9 ALPHA 
Build date: 1981-01-01 01:01:02 
Current date: 2024-09-20 12:41:52 
Device: Realme RMX3231 
 
Stack trace:  
java.lang.IndexOutOfBoundsException: Index: 3, Size: 1
	at java.util.ArrayList.get(ArrayList.java:437)
	at com.tyron.code.language.textmate.BaseIncrementalAnalyzeManager$LockedSpans$ReaderImpl.getSpanAt(BaseIncrementalAnalyzeManager.java:428)
	at io.github.rosemoe.sora.widget.EditorPainter.drawRows(EditorPainter.java:860)
	at io.github.rosemoe.sora.widget.EditorPainter.drawView(EditorPainter.java:464)
	at io.github.rosemoe.sora.widget.EditorPainter.draw(EditorPainter.java:128)
	at io.github.rosemoe.sora.widget.CodeEditor.onDraw(CodeEditor.java:3268)
	at com.tyron.code.ui.editor.impl.text.rosemoe.CodeEditorView.onDraw(CodeEditorView.java:456)
	at android.view.View.draw(View.java:22464)
	at android.view.View.updateDisplayListIfDirty(View.java:21320)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4489)
	at android.view.View.updateDisplayListIfDirty(View.java:21280)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4489)
	at android.view.View.updateDisplayListIfDirty(View.java:21280)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4489)
	at android.view.View.updateDisplayListIfDirty(View.java:21280)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4489)
	at android.view.View.updateDisplayListIfDirty(View.java:21280)
	at android.view.View.draw(View.java:22175)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4532)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4293)
	at android.view.View.updateDisplayListIfDirty(View.java:21311)
	at android.view.View.draw(View.java:22175)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4532)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1312)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4293)
	at android.view.View.updateDisplayListIfDirty(View.java:21311)
	at android.view.View.draw(View.java:22175)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4532)
	at androidx.fragment.app.FragmentContainerView.drawChild(FragmentContainerView.kt:235)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4293)
	at androidx.fragment.app.FragmentContainerView.dispatchDraw(FragmentContainerView.kt:225)
	at android.view.View.updateDisplayListIfDirty(View.java:21311)
	at android.view.View.draw(View.java:22175)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4532)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4293)
	at android.view.View.updateDisplayListIfDirty(View.java:21311)
	at android.view.View.draw(View.java:22175)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4532)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4293)
	at android.view.View.updateDisplayListIfDirty(View.java:21311)
	at android.view.View.draw(View.java:22175)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4532)
	at androidx.drawerlayout.widget.DrawerLayout.drawChild(DrawerLayout.java:1478)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4293)
	at android.view.View.updateDisplayListIfDirty(View.java:21311)
	at android.view.View.draw(View.java:22175)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4532)
	at androidx.fragment.app.FragmentContainerView.drawChild(FragmentContainerView.kt:235)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4293)
	at androidx.fragment.app.FragmentContainerView.dispatchDraw(FragmentContainerView.kt:225)
	at android.view.View.updateDisplayListIfDirty(View.java:21311)
	at android.view.View.draw(View.java:22175)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4532)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4293)
	at android.view.View.updateDisplayListIfDirty(View.java:21311)
	at android.view.View.draw(View.java:22175)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4532)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4293)
	at android.view.View.updateDisplayListIfDirty(View.java:21311)
	at android.view.View.draw(View.java:22175)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4532)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4293)
	at android.view.View.updateDisplayListIfDirty(View.java:21311)
	at android.view.View.draw(View.java:22175)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4532)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4293)
	at android.view.View.updateDisplayListIfDirty(View.java:21311)
	at android.view.View.draw(View.java:22175)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4532)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4293)
	at android.view.View.updateDisplayListIfDirty(View.java:21311)
	at android.view.View.draw(View.java:22175)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4532)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4293)
	at android.view.View.draw(View.java:22467)
	at com.android.internal.policy.DecorView.draw(DecorView.java:811)
	at android.view.View.updateDisplayListIfDirty(View.java:21320)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:565)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:642)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4181)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3908)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3170)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2023)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8314)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
	at android.view.Choreographer.doFrame(Choreographer.java:731)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7948)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:603)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

User actions: 
2024-09-20 12:30:06: MainActivity created
2024-09-20 12:30:06: MainActivity resumed
2024-09-20 12:30:14: MainActivity paused
2024-09-20 12:41:10: MainActivity resumed
2024-09-20 12:41:13: MainActivity paused
2024-09-20 12:41:18: MainActivity resumed
`

**Comment by Scratch2033YT** [comment]
Same :) 👍
