### ISSUE TITLE
Error Opening Project 

### ISSUE THREAD

**Issue by Osalotioman** [tyron12233/CodeAssist#711]
Build version: 0.2.9 ALPHA 
Build date: 1981-01-01 01:01:02 
Current date: 2024-09-30 03:47:07 
Device: OPPO CPH2083 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
	at com.tyron.xml.completion.repository.api.ResourceNamespace.fromPackageName(ResourceNamespace.java:148)
	at com.tyron.xml.completion.repository.ResourceRepository.<init>(ResourceRepository.java:28)
	at com.tyron.completion.xml.XmlRepository.initialize(XmlRepository.java:90)
	at com.tyron.code.ui.project.ProjectManager.doOpenProject(ProjectManager.java:165)
	at com.tyron.code.ui.project.ProjectManager.lambda$openProject$0$com-tyron-code-ui-project-ProjectManager(ProjectManager.java:94)
	at com.tyron.code.ui.project.ProjectManager$$ExternalSyntheticLambda0.run(Unknown Source:10)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

User actions: 
2024-09-30 03:35:22: MainActivity created
2024-09-30 03:35:22: MainActivity resumed
2024-09-30 03:35:22: MainActivity paused
2024-09-30 03:35:24: MainActivity resumed
2024-09-30 03:38:52: MainActivity paused
2024-09-30 03:39:38: MainActivity resumed
2024-09-30 03:43:26: MainActivity paused
2024-09-30 03:44:29: MainActivity resumed
2024-09-30 03:44:57: MainActivity paused
2024-09-30 03:45:23: MainActivity resumed
2024-09-30 03:45:43: MainActivity paused
2024-09-30 03:45:43: MainActivity destroyed
2024-09-30 03:45:45: MainActivity created
2024-09-30 03:45:45: MainActivity resumed

**Comment by Osalotioman** [comment]
Has this project been abandoned due to CodeAssist v3?
