### ISSUE TITLE
Editor crash

### ISSUE THREAD

**Issue by rdm600** [tyron12233/CodeAssist#76]
Build version: 0.1.6 ALPHA 
Build date: 1981-01-01 01:01:02 
Current date: 2021-12-18 20:52:12 
Device: Samsung SM-M215F 
 
Stack trace:  
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.next(ArrayList.java:860)
	at io.github.rosemoe.sora.text.CachedIndexer.afterDelete(CachedIndexer.java:436)
	at io.github.rosemoe.sora.text.Content.dispatchAfterDelete(Content.java:706)
	at io.github.rosemoe.sora.text.Content.delete(Content.java:384)
	at io.github.rosemoe.sora.text.Content.delete(Content.java:295)
	at io.github.rosemoe.sora.widget.EditorInputConnection.deleteSurroundingText(EditorInputConnection.java:293)
	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:456)
	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:93)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8595)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

User actions: 
2021-12-18 20:42:04: MainActivity created
2021-12-18 20:42:04: MainActivity resumed
2021-12-18 20:42:27: MainActivity paused
2021-12-18 20:42:34: MainActivity resumed
2021-12-18 20:42:50: MainActivity paused
2021-12-18 20:46:36: MainActivity resumed
2021-12-18 20:46:39: MainActivity paused
2021-12-18 20:46:41: MainActivity resumed
2021-12-18 20:48:19: MainActivity paused
2021-12-18 20:48:32: MainActivity resumed

This happened when the code with errors was quickly deleted

**Comment by tyron12233** [comment]
This is a bug on the editor please report it on https://github.com/Rosemoe/sora-editor/tree/main/editor/src/main/java/io/github/rosemoe/sora

**Comment by tyron12233** [comment]
A work around is provided by the app, disable the `Enable keyboard suggestions` option
